#101 create api versions
sparcs-kaist/taxi-back pull request #102
Opened 2022-08-10 17:31 UTC by withSang

# Summary 

It closes #101
백엔드에서 특정 API가 변경되었을 때 해당 API에 v2 태그를 붙여 기존 API가 계속 호환되도록 조치했습니다.
예를 들어, /rooms/create의 입력값이 바뀌었다면
- 입력값이 바뀐 새 API는 /rooms/v2/create
- 기존 API는 /rooms/create 를 통해 사용 가능합니다.
빠른 개발을 위해 기존 API는 프론트엔드의 main 브랜치에서 사용하지 않는 대로 바로 삭제하려고 합니다.

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images 
<img width="728" alt="기존 /rooms/search API 요청 결과" src="https://user-images.githubusercontent.com/46402016/183977880-8a2c2378-c538-4523-874a-8bbbbd60e80e.png">

**기존 /rooms/search API 요청 결과**

<img width="726" alt="새 /rooms/v2/search API 요청 결과" src="https://user-images.githubusercontent.com/46402016/183977899-92f4cef3-66be-4373-8ace-ccf96bbcf29d.png">

**새 /rooms/v2/search API 요청 결과**

# Further Work 

- Do something...

2022-08-10 18:22 UTC, 14KGun requested changes
수고하셨습니다~~~ 👍

2022-08-10 18:22 UTC, 14KGun commented on src/route/rooms.v2.js
> +    body("maxPartLength").isInt({ min: 1, max: 4 }),
maxPartLength 범위가 1부터 시작되어야 할 것 같아용

2022-08-10 18:22 UTC, 14KGun commented on src/route/rooms.v2.js
> +    body("maxPartLength").isInt({ min: 1, max: 4 }),
#99 에서 수정 사항이 있네요 ㅎㅎ

2022-08-10 18:22 UTC, 14KGun commented on src/service/rooms.v2.js
> +  }
auth 미들웨어가 하는 역할이 중복되어 있는 것 같아요

2022-08-10 18:22 UTC, 14KGun commented on src/service/rooms.v2.js
> +    let room = await roomModel.findById(req.body.roomId);
`const` 로 정의되어도 될것 같아요

2022-08-10 18:22 UTC, 14KGun commented on src/service/rooms.v2.js
> +    res.send(formatSettlement(room));
상대방이 동의하지 않았는데, 방에 초대가 될 수 있을 것 같아요.
이 api는 리펙토링이 필요해 보입니다.

2022-08-10 18:22 UTC, 14KGun commented on src/service/rooms.v2.js
> +      return;
👍

2022-08-10 18:22 UTC, 14KGun commented on src/service/rooms.v2.js
> +    console.error(err);
`logger`에 추가가 되지 않았네용

2022-08-10 18:22 UTC, 14KGun commented on src/service/rooms.v2.js
> +  }
auth 미들웨어랑 역할이 겹치는 것 같아요

2022-08-10 18:22 UTC, withSang commented on src/route/rooms.v2.js
> +    body("maxPartLength").isInt({ min: 1, max: 4 }),
#99 에서 search까지 다 2,4로 수정했습니다!

2022-08-10 18:23 UTC, withSang commented on src/service/rooms.v2.js
> +    res.send(formatSettlement(room));
그러네요... 이슈 추가로 하나 파서 작업하는 게 낫겠어요

2022-08-10 18:25 UTC, withSang commented on src/service/rooms.v2.js
> +    console.error(err);
헐 디버깅용으로 놔둔 걸 안 지웠어요 미안합니다..
 수정했습니다!

2022-08-10 18:25 UTC, withSang commented on src/service/rooms.v2.js
> +  }
위에도 그렇네요 제거했습니다!

2022-08-10 18:26 UTC, withSang commented on src/service/rooms.v2.js
> +  }
헐 맞네요.. 코드를 통째로 볼 기회가 없었는데 이런 문제도 찾을 수 있군요 감사합니다.

2022-08-10 18:28 UTC, 14KGun approved these changes
수고하셨습니당~~~~

2022-08-11 06:58 UTC, GrasshopperBears approved these changes
작업속도가 엄청나시네요! 수고하셨습니다 🎉

2022-08-11 06:58 UTC, GrasshopperBears commented on src/route/rooms.v2.js
> +    body("maxPartLength").isInt({ min: 1, max: 4 }),
@14KGun  엇 2부터 시작해야 하는거 아니었나요? 프론트는 [2,4]로 설정했는데... 동승을 구하는 건 최소 2명이라 생각했어요

2022-08-11 07:04 UTC, withSang commented on src/route/rooms.v2.js
> +    body("maxPartLength").isInt({ min: 1, max: 4 }),
앗 맞네요 어제 새벽에 @14KGun님이랑 저랑 얘기할 땐 프론트처럼 [2, 4]로 바꿔야 한다고 얘기했었는데 댓글은 다르게 달렸어요!!

2022-08-11 07:25 UTC, xogustlnx approved these changes
수고하셨습니다!

2022-08-11 10:57 UTC, merged

2022-08-11 11:00 UTC, 14KGun commented on src/route/rooms.v2.js
> +    body("maxPartLength").isInt({ min: 1, max: 4 }),
아 @GrasshopperBears 2부터 시작되어야 해요!! 죄송해요ㅜㅜ 오타입니다.