#106 remove static router
sparcs-kaist/taxi-back pull request #123
Opened 2022-08-23 13:08 UTC by withSang

# Summary 

It closes #106 

택시 서비스에서 사용하는 모든 이미지들을 S3에 업로드하게 되면서 기존에 백엔드 서버에 저장된 프로필 사진을 제공하던 /static 라우터의 필요가 없어졌습니다.
또한 어드민 페이지를 추가하면서 /users/getAllUsers와 같은 테스트용 API의 필요가 없어졌으므로 이들을 지우려고 합니다.
또한 프론트엔드에서 더 이상 사용되지 않는 오래된 Room API (일명 v1 API)를 삭제하고, /rooms/로 접근하든 /rooms/v2로 접근하든 무조건 새로운 Room API를 호출하도록 변경합니다.

# Extra info 

- Needs more than 2 reviewers? y
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images 

- 없음.

# Further Work 

- 없음.

2022-08-23 15:11 UTC, 14KGun requested changes
👍

2022-08-23 15:11 UTC, 14KGun commented on src/route/docs/rooms.v2.md
> +### `/settlement/` **(POST)**
`commitSettlement`로 수정되어야 할 것 같아용

2022-08-23 15:11 UTC, 14KGun commented on src/route/rooms.v2.js
> +  body("id").isMongoId(),
`"roomId"`로 수정되어야 할 것 같아요!

2022-08-23 15:11 UTC, 14KGun commented on src/route/rooms.v2.js
> +  body("id").isMongoId(),
`"roomId"`로 수정되어야 할 것 같아요!

2022-08-24 13:03 UTC, 14KGun reviewed
수고하셨습니다~

2022-08-24 13:09 UTC, withSang commented on src/route/rooms.v2.js
> -router.get("/removeAllRoom", roomHandlers.removeAllRoomHandler);
cypress 테스트 케이스도 이거 지우고 삭제하면 될 것 같아요! 혹시 백엔드에서 먼저 지워도 문제가 없을까요? @GrasshopperBears
아니면 이 부분은 남겨놓고 머지해도 됩니다!

2022-08-24 13:14 UTC, GrasshopperBears commented on src/route/rooms.v2.js
> -router.get("/removeAllRoom", roomHandlers.removeAllRoomHandler);
독립 환경에서 테스트 할거라면 지워도 상관 없을 것 같습니다!

2022-08-24 13:18 UTC, GrasshopperBears approved these changes
시원하네요ㅎㅎ

2022-08-24 13:18 UTC, GrasshopperBears commented on src/route/rooms.v2.js
> +// router.post(
혹시 나중에 사용된다면 `PATCH`로 바꾸면 좋을 것 같습니다!

2022-08-24 13:25 UTC, withSang commented on src/route/rooms.v2.js
> -router.get("/removeAllRoom", roomHandlers.removeAllRoomHandler);
아하 그러면 백엔드에서는 먼저 지울게요! 감사합니다

2022-08-25 14:16 UTC, 14KGun approved these changes
LGTM!

2022-08-25 14:42 UTC, merged