Add: reportShcema
sparcs-kaist/taxi-back pull request #131
Opened 2022-09-06 14:44 UTC by ptptsw

# Summary 

It closes #118 

신고 시스템 구현

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images 

# Further Work 

- Do something...

2022-09-06 16:03 UTC, withSang commented
우와 좋은 것 같습니다!!! 그러고보니 `reportedId`와 `reporterId`가 나중에 코드로 보았을 때 헷갈릴 수도 있을 것 같아요. `creatorId`는 어떨까요?

2022-09-07 18:07 UTC, GrasshopperBears commented on src/db/mongo.js
> +  etcDetail: { type: String, default: "" }, // 기타 세부 사유
세부 사유는 `type`이 `"etc-reason"`일 때만 받나요?
`"no-settlement"`, `"no-show"`에도 간략한 설명을 추가할 수도 있을 것 같아 질문합니다!

2022-09-21 11:48 UTC, withSang commented on src/route/users.js
> +router.post("/report", userHandlers.reportHandler);
request body의 `reportedId`, `type`, `etcDetail`, `time`에 대한 입력값 검증 미들웨어들이 필요합니다!

2022-09-21 14:04 UTC, withSang requested changes
잘 돌아가네요 수고하셨습니다!! 남겨드린 리뷰 확인해주시면 감사하겠습니다 :)

2022-09-27 04:35 UTC, withSang approved these changes
우와 수고하셨습니다!! 😊

2022-09-27 14:36 UTC, 14KGun reviewed
수고하셨습니다 ~~

2022-09-27 14:36 UTC, 14KGun commented on src/service/users.js
> +    console.log(creatorId, reportedId);
`console.log` 지워주세요 ~~

2022-09-27 14:36 UTC, 14KGun commented on src/service/users.js
> +    let report = new reportModel({
`const`로 정의하여도 괜찮을 것 같아요

2022-10-04 08:10 UTC, 0ev submitted a review, later dismissed

2022-10-04 08:10 UTC, 0ev commented on src/service/users.js
> +    res.send(200).send("User/report : report successful");
```suggestion
    res.status(200).send("User/report : report successful");
```
이렇게 안하면 계속 crash 하네요

2022-10-04 13:35 UTC, 14KGun approved these changes
수고하셨습니다 ~~ 👍 👍

2022-10-04 14:12 UTC, GrasshopperBears approved these changes
👍 수고하셨습니다~

2022-10-05 07:16 UTC, merged