Refactor: handle space in nickname
sparcs-kaist/taxi-back pull request #138
Opened 2022-09-20 15:42 UTC by Hyogyeong8

# Summary 

It closes #136 

# Extra info 

- Needs more than 2 reviewers? n
- Needs more than 10 minutes for review? n
- Needs to execute in order to review? n

2022-09-21 11:39 UTC, withSang commented on src/route/users.js
> +    .customSanitizer((value) => replaceSpaceInNickname(value))
customSanitizer의 파라미터에서 `(value) => replaceSpaceInNickname(value)`로 함수로 한 번 더 감싸실 필요 없이 `replaceSpaceInNickname`를 파라미터로 바로 넘기셔도 잘 작동해요!

2022-09-21 11:47 UTC, withSang requested changes
오 너무 잘 되네요 수고하셨습니다! 👍 
아래쪽에 댓글을 남겨드렸는데, 머지 전에 확인해주시면 감사하겠습니다!

2022-09-23 08:26 UTC, withSang approved these changes
우왕 버그 찾으시고 수정까지 하시다니 수고 많으셨습니다! 👍

2022-09-23 08:28 UTC, merged

2022-09-23 08:31 UTC, Hyogyeong8 commented
공백 3개 입력 시 matches 되지 않아 400 error로 반환됨
-> error 세분화해서(?) front에 alert 해야할 것 같아요

이 부분은 어떻게 할까요??

2022-09-23 10:50 UTC, withSang commented
> 공백 3개 입력 시 matches 되지 않아 400 error로 반환됨 -> error 세분화해서(?) front에 alert 해야할 것 같아요
> 
> 이 부분은 어떻게 할까요??

저는 공백 3개도 닉네임 규칙에 맞지 않는 이름이니까 400 error를 반환하는 게 맞다고 생각했어요!