Add: 앱 자동 로그인 구현
sparcs-kaist/taxi-back pull request #142
Opened 2022-09-27 14:27 UTC by happycastle114

# Summary 

It closes #134 

# Extra info 

- Needs more than 2 reviewers? y
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Images

2022-10-27 00:09 UTC, 14KGun requested changes
수고하셨습니다 ~~~

2022-10-27 00:09 UTC, 14KGun commented on src/service/auth.js
> +    if (data == TOKEN_INVALID) {
노션 룰에 따라 js에서는 `===`로 비교하시는 것이 좋을 것 같습니다 ~

2022-10-27 00:09 UTC, 14KGun commented on src/service/auth.js
> +      return;
음... 위 코드랑 동일하게 `return res.status(401)...`로 수정하시거나.
아니면 if else문 사용하시면 좋을 것 같아요

2022-10-27 00:09 UTC, 14KGun commented on src/service/auth.js
>    res.redirect(security.frontUrl + "/login/false"); // 리엑트로 연결되나?
리엑트로 연결 됩니다. 누가 주석 단거죠?? ㅋㅋㅋ

@withSang

2022-10-27 00:09 UTC, 14KGun commented on src/service/auth.js
> +    if (!(data.type == 'access')) {
조건문 `if (data.type !== 'access')`로 수정하셔도 될 것 같습니다

2022-10-27 00:09 UTC, 14KGun commented on src/service/auth.js
> +    console.log(e);
에러 처리 logging은 "/modules/logger" 사용하시면 됩니다

2022-10-27 00:09 UTC, 14KGun commented on src/service/auth.js
> +  // const userData = getLoginInfo(req);
주석 지워주세요 😄

2022-10-27 00:09 UTC, 14KGun commented on src/service/auth.js
> +  if (!accessToken || !refreshToken) return res.status(400).send("invalid request");
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

HTTP status code 규격 확인 부탁드립니다 !!

2022-10-27 00:09 UTC, 14KGun commented on src/service/auth.js
> +      res.status(500).send(e);
back의 에러 내용은 client에 보내면 안되는 정보일 것 같습니다 !!

2022-10-27 03:47 UTC, GrasshopperBears commented on app.js
> +const { initializeApp } = require('firebase-admin/app');
?

2022-10-27 04:12 UTC, GrasshopperBears commented on src/service/auth.js
> +    if (accessTokenStatus == TOKEN_INVALID) {
이하 조건절들 `===`으로 수정해주세요

2022-10-27 04:12 UTC, GrasshopperBears commented on src/service/auth.js
> +    res.status(200).send({ accessToken: newAccessToken.token, refreshToken: newRefreshToken.token });
```suggestion
    res.json({ accessToken: newAccessToken.token, refreshToken: newRefreshToken.token });
```
위와 같은 방식도 가능합니다

2022-10-27 04:12 UTC, GrasshopperBears commented on src/service/auth.js
> +    console.log(id, token);
지워주세용

2022-11-01 06:38 UTC, happycastle114 commented on app.js
> +const { initializeApp } = require('firebase-admin/app');
본래 Firebase를 사용해서 키를 발급하고자 했어서 추가하였으나, 사용하지 않아서 지워야했지만 지우는 것을 잊어버렸습니다..! 이번 PR에서는 지우고 알림 쪽에서 다시 import 하도록 하겠습니다.

2022-11-01 06:39 UTC, happycastle114 commented on .env.example
> +JWT_SECRET_KEY=[JWT SERCRET KEY]
추가했습니다 :)

2022-11-01 11:23 UTC, happycastle114 commented on src/modules/jwt.js
> +        },
수정했습니다!

2022-11-01 11:26 UTC, happycastle114 commented on src/route/auth.js
> +router.route("/login/app").get(authHandlers.sparcsssoForAppHandler);
수정했습니다! 감사합니다.

2022-11-01 11:36 UTC, happycastle114 commented on src/service/auth.js
> +    if (!(data.type == 'access')) {
수정했습니다!

2022-11-01 11:36 UTC, happycastle114 commented on src/service/auth.js
> +    if (data == TOKEN_INVALID) {
수정했습니다!

2022-11-02 00:35 UTC, 14KGun commented on src/config/secretKey.js
> +}
`prettier` 적용해주세요!

2022-11-02 00:35 UTC, 14KGun commented on src/modules/jwt.js
> +const option = require('../config/secretKey').option;
```
const { secretKey, option } = require('../config/secretKey');
```

로 사용하시면 더 깔끔하게 사용하실 수 있을 것 같아요

2022-11-02 00:35 UTC, 14KGun commented on src/route/auth.js
> +router.route("/app/token/generate").get(authHandlers.sparcsssoForAppHandler);
👍

2022-11-02 00:35 UTC, 14KGun commented on src/modules/jwt.js
> +const TOKEN_INVALID = -2;
이 상수들도 외부에서 `exports`해서 사용하면 좋을 것 같아요

2022-11-02 00:35 UTC, 14KGun commented on src/service/auth.js
> +        res.redirect( "org.sparcs.taxiApp://login?accessToken=" + accessToken.token + "&refreshToken=" + refreshToken.token);
`prettier` 적용해주세요!

2022-11-02 00:35 UTC, 14KGun commented on src/service/auth.js
> +const TOKEN_INVALID = -2;
`jwt.js` 에서 불러와 정의하면 좋을 것 같아요
(위 리뷰 참고)

2022-11-02 00:36 UTC, 14KGun reviewed
수고하셨습니다 ~~~

리뷰 다시 한번 확인해주세요 😄

2022-11-02 15:17 UTC, withSang commented on src/route/auth.js
> +router.route("/app/token/generate").get(authHandlers.sparcsssoForAppHandler);
오 CRUD에 맞춰서 구현하시니 사용하기에도 편할 것 같아요 ㅎㅎ

2022-11-06 06:41 UTC, 14KGun approved these changes
수고하셨습니다 ~~ 👍 👍

2022-11-06 06:41 UTC, 14KGun commented on src/service/auth.js
> +      res.redirect(security.frontUrl + "/");
꼭 "/" 붙여야 하나요??

2022-11-06 06:43 UTC, 14KGun commented
@happycastle114 추가적으로 각 API에 대한 설명도 [auth API doc]\(https://github.com/sparcs-kaist/taxi-back/blob/%23134-%EC%95%B1-%EC%9E%90%EB%8F%99-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B5%AC%ED%98%84/src/route/docs/auth.md)에 추가하셔야 해요!!

작성 부탁드립니다

2022-11-08 14:41 UTC, GrasshopperBears commented on src/db/mongo.js
> +  deviceTokenModel: mongoose.model("Token", deviceTokenSchema),
모델 이름을 `"DeviceToken"`으로 하는건 어떨까요?

2022-11-08 14:44 UTC, GrasshopperBears commented on src/modules/jwt.js
> +    } else if (err.message === "invalid token") {
https://www.npmjs.com/package/jsonwebtoken#errors--codes
문서에는 이러한 메세지가 없는 것 같아요... 실제 발생하는 에러인가요?

2022-11-08 14:50 UTC, GrasshopperBears commented on src/service/auth.js
> +  userModel.findOne(
async 함수니까 await 쓰면 더 보기 좋을 것 같습니다

2022-11-16 20:51 UTC, happycastle114 commented on src/service/auth.js
> +  userModel.findOne(
async를 넣어두고는 사용하지 않아서..ㅜㅜ 삭제했습니다..!

2022-11-16 20:53 UTC, happycastle114 commented on src/modules/jwt.js
> +    } else if (err.message === "invalid token") {
어...그렇네요... 수정했습니다..! 감사합니다 :)

2022-11-16 20:54 UTC, happycastle114 commented on src/db/mongo.js
> +  deviceToken: { type: Schema.Types.Array, required: true },
수정했습니다 :) 감사합니다!

2022-11-28 10:58 UTC, 14KGun reviewed
늦은 리뷰 죄송합니다.
빠르게 후다닥 처리하시고 머지 하시죠~

2022-11-28 10:58 UTC, 14KGun commented on src/route/auth.js
> +router.route("/app/token/generate").get(authHandlers.sparcsssoForAppHandler);
`route url`이랑 `handler` 이름도 통일되면 좋을 것 같아요

2022-11-28 11:00 UTC, 14KGun commented on src/route/auth.js
> +router.route("/app/token/generate").get(authHandlers.sparcsssoForAppHandler);
https://github.com/sparcs-kaist/taxi-back/blob/a3fe3fd5c6cf868411b8e5bef6380a36e79c29d1/src/route/auth.js#L9-L13

이렇게요

2022-12-02 08:41 UTC, 14KGun approved these changes
수고하셨습니다 👍 👍

2022-12-02 08:41 UTC, 14KGun commented on src/modules/jwt.js
> +};
`option`이 `reference` 일 것 같은데,
요청들이 비동기로 처리될려면, `option` `deep copy` 한 번 해야 하지 않을까요?

2022-12-02 08:44 UTC, 14KGun commented on src/service/auth.js
> +          createNewTokenHandler(req, res, userData);
토큰 만들고 redirect 해서 다시 로그인 시도하게 하는 로직 아닌가요??
(제가 맞게 이해 했나요?? ㅎ)

@happycastle114

2022-12-05 18:34 UTC, merged