#156 move rooms to the past room list and change settlestatus automatically when the participant is one
sparcs-kaist/taxi-back pull request #194
Opened 2022-11-25 15:07 UTC by Hyogyeong8

# Summary 

It closes #156 

# Further Work 

[ ] searchByUserHandler

2022-11-25 15:10 UTC, Hyogyeong8 commented
searchByUserHandler말고 또 고쳐야 할 함수가 있을까요?
그리고 정산 완료로 바꾸고, 과거 참여방으로 이동시키는 것 외에 채팅을 닫는다던가 하는 작업들은 필요 없나요?

2022-11-25 15:12 UTC, Hyogyeong8 commented on src/service/rooms.js
> +      }
기존에 작성되어 있는 commitPaymentHandler() 함수를 참고해서 작성했는데 이 부분에서 App Crash가 납니다. 도와주세요

2022-11-25 15:13 UTC, Hyogyeong8 commented on src/service/rooms.js
> +      await user.save();
기존에 작성되어 있는 commitPaymentHandler() 함수를 참고해서 작성했는데 이 부분에서 App Crash가 납니다. 도와주세요

2022-11-25 15:16 UTC, Hyogyeong8 commented on src/service/rooms.js
> +      await user.save();
기존에 작성되어 있는 commitPaymentHandler() 함수를 참고해서 작성했는데 이 부분에서 App Crash가 납니다. 도와주세요

2022-11-26 02:09 UTC, 14KGun commented
@imYourChoi 이거 back에서 처리하면 front에서 내 방 정보 수정되었는지 감지할 수 있는 로직이 있을까요??

(생각난 해결 방안으로는, front에서 택시 출발시각 지났고 혼자 참여 중이면 자동으로 back에 정산하기 api 호출하는 방안이 있기는 합니다.)

2022-11-26 02:16 UTC, 14KGun commented on src/service/rooms.js
> +      await user.save();
https://constructionsite.tistory.com/43

참고 부탁드려요 ~

2022-11-26 02:16 UTC, 14KGun commented on src/service/rooms.js
> +      await user.save();
forEach에서는 await 사용해도 의미가 없습니다 ㅜ

2022-11-26 05:04 UTC, imYourChoi commented
@14KGun 지금 생각나는 거는 그 작업을 Skeleton에서 path 바뀔때마다 그 방법을 해주는 수 밖에는 없는것 같은데 비효율적인것 같기는 하네요

2022-11-26 16:34 UTC, Hyogyeong8 commented on src/service/rooms.js
> +      await user.save();
for of로 로직을 바꾸었는데도 user.save is not a function 에러가 뜨고, user.save()를 주석 처리해도 실행이 안됩니다. for of 안에서 user를 프린트하는 건 됩니다.

2022-11-29 05:04 UTC, Hyogyeong8 commented on src/service/rooms.js
>        .lean();
와... 속시원하네요. 감사합니다

2022-11-30 02:17 UTC, Hyogyeong8 commented
지금 상태로는 내 방 확인을 해야만 이 기능이 구현됩니다. 좀 더 정확한 구현을 위해서는 rooms/join API 안에서도 한 번 더 이 기능을 구현해야 할 것 같습니다. (현재 참여 중인 방이 5개 이상이라고 오류를 보내기 전에) 하지만 그렇게 하면 코드가 길어질 것 같아서 넣을지 고민하고 있습니다.

2022-12-01 12:11 UTC, Hyogyeong8 commented
> > 지금 상태로는 내 방 확인을 해야만 이 기능이 구현됩니다. 좀 더 정확한 구현을 위해서는 rooms/join API 안에서도 한 번 더 이 기능을 구현해야 할 것 같습니다. (현재 참여 중인 방이 5개 이상이라고 오류를 보내기 전에) 하지만 그렇게 하면 코드가 길어질 것 같아서 넣을지 고민하고 있습니다.
> 
> 네네, 수고하셨습니다만.... 😢 front에서 내가 정산이 자동으로 되었는지 확인할 수 있는 로직이 없어. 아직 머지되면 않될 듯 합니다 !!
> 
> @Hyogyeong8 , @imYourChoi

죄송하지만 이해가 잘 안 갑니다ㅠㅠ front에서 정산이 되었는지를 확인해야 하나요? back에서 정산 완료시킨 방을 반환하면 되는 게 아닌가요? 로직이 완전하지 않아서 머지 안 되어도 저는 상관 없습니다:)

2022-12-02 02:22 UTC, 14KGun commented
> > > 지금 상태로는 내 방 확인을 해야만 이 기능이 구현됩니다. 좀 더 정확한 구현을 위해서는 rooms/join API 안에서도 한 번 더 이 기능을 구현해야 할 것 같습니다. (현재 참여 중인 방이 5개 이상이라고 오류를 보내기 전에) 하지만 그렇게 하면 코드가 길어질 것 같아서 넣을지 고민하고 있습니다.
> > 
> > 
> > 네네, 수고하셨습니다만.... 😢 front에서 내가 정산이 자동으로 되었는지 확인할 수 있는 로직이 없어. 아직 머지되면 않될 듯 합니다 !!
> 
> 죄송하지만 이해가 잘 안 갑니다ㅠㅠ front에서 정산이 되었는지를 확인해야 하나요? back에서 정산 완료시킨 방을 반환하면 되는 게 아닌가요? 로직이 완전하지 않아서 머지 안 되어도 저는 상관 없습니다:)

front 에서 roomlist를 확인 하는 API를 최대한 효율적으로 호출할려고 매번 저 API를 호출하지 않습니다. ㅜ
자신이 방에 참가하였을 때, 정산/결제 요청을 하였거나 방을 나갔을 때 만 roomlist API를 호출하여 내 방 정보를 update 하고 있습니다.

근데, 저 세 조건에 만족하지 않았는데 back에서 내 방 정보를 update한다면, front 에서 가지고 있는 내 방 정보랑 back의 db에 저장되어 있는 내용이랑 conflict이 날 것 같습니다.

@Hyogyeong

2025-02-04 18:19 UTC, kmc7468 requested changes
수고하셨습니다..! 코멘트 확인 후 수정 부탁드려요

2025-02-04 18:20 UTC, kmc7468 commented
cron으로 일정 시간 간격으로 자동 정산 처리를 진행할거면, searchByUserHandler에서 해당 작업을 또 할 필요는 없지 않을까요? @TaehyeonPark

2025-02-05 16:34 UTC, kmc7468 requested changes
수고하셨습니다! 로직에는 문제가 없어보이지만, 변경 요청 사항 확인 부탁드립니다

2025-02-05 16:34 UTC, kmc7468 commented on src/routes/docs/rooms.js
> +    혼자 참여 중인 방 중 이미 출발한 방이 있으면 정산 완료 처리한 후 과거 참여 방으로 옮긴다.`,
이거 이제 더 이상 필요 없는 설명인 것 같습니다

2025-02-05 16:34 UTC, kmc7468 commented on src/services/rooms.js
> +    let user = await userModel
user를 밑에서 바꿀 일이 없으니 다시 const로 바꿔주면 좋을 것 같아요!

2025-02-05 16:34 UTC, kmc7468 commented on src/schedules/autoProcessingRoom.js
이 파일 혹시 TS로 작성 가능할까요? 새로운 파일은 아예 TS로 작성하는게 바람직할 것 같네요..

2025-02-05 16:34 UTC, kmc7468 commented on src/schedules/autoProcessingRoom.js
> +    const expiredDate = new Date(Date.now() - 60 * MS_PER_MINUTE).toISOString();
60분인 이유가 있을까요??

2025-02-05 16:34 UTC, kmc7468 commented on src/schedules/autoProcessingRoom.js
> +        { "part.0.settlementStatus": { $nin: ["paid", "sent"] } }, // "sent"의 경우 로직상 불가능 하지만, 문서화 측면에서 의도적으로 남겨두었음음.
음음

2025-02-05 16:34 UTC, kmc7468 commented on src/schedules/autoProcessingRoom.js
> +        await roomModel.findByIdAndUpdate(roomId, {
경합 조건을 더 엄격하게 제어하려면, `part.0.settlementStatus` 값이 `not-departed` 인 경우에만 update하도록 수정하고, update에 성공한 경우 emitChatEvent / 아래에 있는 pull/push 쿼리 실행을 하는게 더 좋지 않을까요? (mongoose에서 구현이 가능한진 모르겠어서 검토가 필요할 것 같습니다)

2025-02-05 17:12 UTC, TaehyeonPark commented on src/schedules/autoProcessingRoom.js
> +        { "part.0.settlementStatus": { $nin: ["paid", "sent"] } }, // "sent"의 경우 로직상 불가능 하지만, 문서화 측면에서 의도적으로 남겨두었음음.
음이 두 번 들어갔네 ㅋㅋ;;

2025-02-05 17:12 UTC, TaehyeonPark commented on src/schedules/autoProcessingRoom.js
> +    const expiredDate = new Date(Date.now() - 60 * MS_PER_MINUTE).toISOString();
깔끔하게 한 시간으로 하는게 좋을것 같았습니다..!

2025-02-05 17:58 UTC, TaehyeonPark commented on src/schedules/autoProcessingRoom.js
> +        await roomModel.findByIdAndUpdate(roomId, {
이 부분은 안 하기로 논의됨

2025-02-05 18:11 UTC, kmc7468 approved these changes
LGTM! 수고하셨습니다!

2025-02-05 18:20 UTC, merged