#263 채팅 socket 구조 개편
sparcs-kaist/taxi-back pull request #268
Opened 2023-04-04 13:54 UTC by chlehdwon

# Summary 

It closes #263

2023-04-11 18:24 UTC, 14KGun requested changes
수고하셨습니다 !!! 👍 👍

2023-04-11 18:24 UTC, 14KGun commented on src/services/chats.js
> +    }
socket 연결 여부는 

```suggestion
    const { socketId } = req.session;
    if (!socketId || !io) {
      return res.status(403).send("Chat/ : socket did not connected");
    }
```

로 확인해야 할 것 같아요

2023-04-11 18:24 UTC, 14KGun commented on src/services/chats.js
> +      });
동일한 아이디의 사용자가 여러 디바이스로 접속했을 수 있습니다.
"API"의 결과 값은 `io.to(socketId)`로 보내는 것이 좋을 것 같아요!

2023-04-11 18:24 UTC, 14KGun commented on src/services/chats.js
> +        roomId,
`chats` 배열 요소 안에 `roomId`가 있어서 클라이언트로 안넘겨줘도 될 것 같아요!

2023-04-11 18:24 UTC, 14KGun commented on src/modules/socket.js
> +      const userId = session.userId;
```suggestion
      const { id: userId } = getLoginInfo({ session });
```

2023-04-11 18:24 UTC, 14KGun commented on src/services/chats.js
> +      .limit(60)
60은 공통적으로 사용되는 상수이므로 따로 빼서 정의하면 좋을 것 같아요

2023-04-11 18:24 UTC, 14KGun commented on src/services/chats.js
> +    const user = await userModel.findOne({ id: userId });
`user` 사용되지 않아서 정의하지 않아도 될 것 같아요 !

2023-04-24 16:55 UTC, chlehdwon commented on src/routes/chats.js
> +  "/",
앜ㅋㅋㅋㅋ 일단은 그대로 두고 혼동 온다 싶을 시 변경하도록 하겠습니다!

2023-04-24 17:00 UTC, chlehdwon commented on src/routes/chats.js
> +  body("type").matches(patterns.chat.chatType),
아하 그렇군요 다른 type들은 다른 api에서 처리해서 괜찮군요! 수정하겠습니당

2023-04-25 08:37 UTC, 14KGun reviewed
수고하셨습니다 👍 👍 😄

2023-04-25 08:37 UTC, 14KGun commented on src/modules/socket.js
> +    const { roomId, type, content, authorId } = chat;
```suggestion
    const { roomId, type, content, authorId } = chat;
    if (!io || !roomId || !type || !content || !authorId) {
      throw new IllegalArgumentsException();
    }

    const { roomId, type, content, authorId } = chat;
```

로 바꿀 수 있을 듯요!

2023-04-25 08:37 UTC, 14KGun commented on src/modules/socket.js
> +    }
```suggestion
    const { nickname, profileImageUrl } = await userModel.findById(
      authorId,
      "nickname profileImageUrl"
    );
    const { name, part } = await roomModel.findById(roomId, "name part");
    if (!nickname || !profileImageUrl || !name || !part) {
      throw new IllegalArgumentsException();
    }
```

아래 room 검색 코드를 위로 올리고 검색 결과 확인도 하면 좋을 것 같아요

2023-04-25 08:37 UTC, 14KGun commented on src/modules/socket.js
> +    );
```suggestion
    // 방의 모든 사용자에게 socket 메시지 수신 이벤트를 발생시킵니다.
    const chatsForRoom = await transformChatsForRoom([chatDocument]);
    await Promise.all(
      userIds.map(async (userId) =>
        io.to(`user-${userId}`).emit("chat_push_back", {
          chats: chatsForRoom,
          roomId,
        })
      )
    );
```

주석 설명이 잘못되었고, `transformChatsForRoom`를 `Promise.all` 밖으로 빼면 연산 수가 줄어들 것 같습니다 !

2023-04-25 08:37 UTC, 14KGun commented on src/modules/socket.js
> +        const userId = session.userId;
```suggestion
        const { userId } = session;
```

2023-04-25 08:39 UTC, 14KGun commented
아직 front 쪽 코드가 완성이 안되어 있어서,
[front 503 이슈](https://github.com/sparcs-kaist/taxi-front/pull/504) 완성되고 문제 없으면 머지되어도 좋을 것 같아요 !!!

2023-04-25 09:59 UTC, 14KGun commented on src/services/chats.js
>    uploadChatImgDoneHandler,
지금 해당 방에 API 를 호출한 유저가 포함되어 있는지 확인을 하나요??

2023-04-25 10:08 UTC, 14KGun commented on src/services/chats.js
> +      res.json({ result: false });
`res.json({ result: false });` 보다는 `return res.status(500).send("Chat/ : internal server error");` 이 front에서 에러 탐지하기 좋을 것 같아요

2023-04-25 10:40 UTC, 14KGun commented on src/modules/socket.js
> +    socket.on("disconnect", async () => {
위 리뷰와 동일합니닷

2023-04-25 10:50 UTC, 14KGun commented on src/routes/chats.js
> +
`body("content")`도 validation 검사 해야하지 않나요 ?? 🤔 🤔

2023-04-25 15:15 UTC, chlehdwon commented on src/modules/socket.js
> +        socket.leave(`user-${userId}`);
앗 그러면 `socket.leave(`user-${userId}`);` 이 부분은 지워도 되는 부분일까요? @14KGun

2023-04-25 15:52 UTC, chlehdwon commented on src/routes/chats.js
> +
chatSchema와 같은 조건으로 validation 검사 진행하도록 할게요~!

2023-04-25 16:27 UTC, chlehdwon commented on src/services/chats.js
>    uploadChatImgDoneHandler,
앗 그렇군요! 수정하도록 하겠습니다!!

2023-04-25 16:27 UTC, chlehdwon reviewed
수정하였습니다!!

2023-04-25 20:44 UTC, 14KGun commented on src/services/chats.js
> +
```suggestion
const isUserInRoom = async (userId, roomId) => {
  const room = await roomModel.findOne({ _id: roomId, part: { userId } }, "_id");
  return !!room;
};
```

한 번의 DB 쿼리 연산으로 user가 방에 포함되어 있는지 여부를 확인할 수 있을 것 같습니다.

2023-04-26 06:26 UTC, 14KGun commented on src/services/chats.js
> +      authorId: userId,
`emitChatEvent` 의 `authorId` 인자는 오브젝트 아이디를 넘겨주어야 하는 것 같아요.

```javascript
const user = await userModel.findOne({ id: req.userId });
if (!user) return res.status(500).send("Chat/send : internal server error");

...

const result = await emitChatEvent(io, {
  roomId,
  type,
  content,
  authorId: user._id,
});
```

2023-04-26 06:33 UTC, 14KGun commented on src/modules/socket.js
> +    );
여기서 `userId`는 오브젝트아이디이고 유저가 실제로 구독한 방은 `user-{유저의 id}` 인 것 같아요

2023-04-26 08:05 UTC, 14KGun commented on src/services/chats.js
> +      chats.reverse();
`loadAfter`는 `loadBefore`과 다르게
DB 검사할 때 오름차순으로 검사하고 `chats.reverse()` 안해줘야 할 것 같아요

2023-04-26 08:11 UTC, chlehdwon commented on src/services/chats.js
> +      authorId: userId,
그렇군요! 저는 다 object id로 생각하고 있었어요 😢

2023-04-26 08:16 UTC, chlehdwon commented on src/services/chats.js
> +
part가 object가 아니라 object의 배열이어도 저렇게 해서 찾을 수 있나요? @14KGun

2023-04-26 08:26 UTC, 14KGun commented
버그 수정하고 https://github.com/sparcs-kaist/taxi-front/pull/504
와 잘 통신되는지 확인해봐야 할 것 같습니다 ㅜ

2023-04-26 08:27 UTC, chlehdwon commented on src/modules/socket.js
> +    );
처음에 connection에서는 user Id로 하고 여기서는 user ObjectId로 하네요..! 그렇다면 처음에 구독할 때 oid로 구독하도록 고칠게요 @14KGun

2023-04-28 05:25 UTC, 14KGun approved these changes
저엉말!! 고생 많으셨습니다 ~!!!! 👍 👍 😄 

LGTM !! 👍

2023-04-28 05:26 UTC, merged