#303 introduce aws ses
sparcs-kaist/taxi-back pull request #304
Opened 2023-05-29 13:19 UTC by chlehdwon

# Summary 

It closes #303

2023-07-28 18:49 UTC, 14KGun commented on loadenv.js
> +  slackWebhookUrl: process.env.SLACK_WEBHOOK_URL || ""
환경변수와 변수명이 더 구체적이어도 좋을 것 같아요!
(신고 접수를 위한 슬랙 웹훅이라는 정보가 포함되면 좋을 것 같습니다 😄)

```suggestion
  slackWebhookUrl: { report: process.env.SLACK_REPORT_WEBHOOK_URL || "" }
```

2023-07-28 18:49 UTC, 14KGun commented on src/modules/stores/mongo.js
> +  roomId: { type: Schema.Types.ObjectId, ref: "Room"} // 신고한 방 id
prettier 적용이 안되어 있는 것 같군요 😅

2023-07-28 18:49 UTC, 14KGun commented on src/services/reports.js
> +    if(report.type==="no-settlement"){
마찬가지로, prettier 적용이 안되어 있는 것 같습니다 ㅜ 😅

2023-07-28 18:49 UTC, 14KGun commented on src/services/reports.js
> +    const { reportedId, type, etcDetail, time, roomId } = req.body;
검증기에서 `roomId` 확인하지 않는 것 같아요

https://github.com/sparcs-kaist/taxi-back/blob/3af10e97a82ac507287b3b97f728657b8d5c0255/src/routes/reports.js#L10-L15

https://github.com/sparcs-kaist/taxi-back/blob/3af10e97a82ac507287b3b97f728657b8d5c0255/src/routes/docs/reportsSchema.js#L1-L26

또한 핸들러 내부에서는 `roomId`가 optional 하게 쓰일지 아닌지에 대한 여부도 확인하면 좋을 것 같습니다 ~

2023-07-28 18:49 UTC, 14KGun commented on src/services/reports.js
> +
`room`을 핸들러 상단에서 먼저 찾고 가는 로직도 괜찮을 것 같아요 (??)

```suggestion
    const room = await roomModel.findById(roomId);
    if (!room) return res.status(400).json({ error: "User/report: no corresponding room" });
    
    if (report.type === "no-settlement" && room) {
      const emailHtml = emailPage(reported.name, reported.nickname, room.name, user.nickname, roomId)
      sendReportEmail(user.nickname, reported.email, report, emailHtml);
    }

```

2023-07-28 18:49 UTC, 14KGun commented on src/modules/stores/aws.js
> +};
`aws` 모듈에서는 슬랙 웹훅 기능은 따로 빼고.. ,
이메일 전송 기능에만 집중하는게 깔끔할지도???

```js
// modules/stores/aws.js
module.exports.sendReportEmail = (fromEmail, toEmail, title, html) => { ... }

/*
만약 callback 함수 필요하면(?) 제가 추천드리는 로직은
const sendReportEmail = (fromEmail, toEmail, title, html, cb) => { ... } 
sendReportEmail(..., (err, data) => { ...after send email... })

또는

const sendReportEmail = async (fromEmail, toEmail, title, html) => { ... } 
sendReportEmail(...).then((value) => { ...after send email... })
*/

// modules/slackNotification.js
const { slackWebhookUrl } = require("../../../loadenv");
module.exports.notifyToReportChannel = (content) => {
  if (!slackWebhookUrl) return;
  ...
}
```

이러면 두 로직이 독립적이라 미정산 신고가 아니어도 슬랙 웹훅으로 알림 받을 수 있을 것 같아요!

2023-07-28 18:51 UTC, 14KGun commented on src/modules/stores/aws.js
> +      logger.info("Email sent successfully");
❤️

2023-08-01 12:54 UTC, chlehdwon commented on src/services/reports.js
> +    const { reportedId, type, etcDetail, time, roomId } = req.body;
roomId가 request에 없을 경우 뒤에 로직상 이 부분에서만 사용하고 예외처리가 다음과 같이 될텐데 추가적으로 확인해야 할 것이 있을까요??
https://github.com/sparcs-kaist/taxi-back/blob/3af10e97a82ac507287b3b97f728657b8d5c0255/src/services/reports.js#L31-L33

2023-08-01 12:57 UTC, chlehdwon commented on src/services/reports.js
> +
이 부분도 고려했는데 위에서 말한 것처럼 roomId가 option으로 정의돼서 위에 로직을 사용했습니다. 어차피 front 코드 변경되면 roomId가 사실상 required가 될 것 같은데 아래 로직으로 바꿀까요??

2023-08-01 12:57 UTC, chlehdwon commented on loadenv.js
> +  slackWebhookUrl: process.env.SLACK_WEBHOOK_URL || ""
앞으로 확장성 면에서 훨씬 좋겠네요! 수정하겠습니다 :)

2023-08-01 12:58 UTC, chlehdwon commented on src/modules/stores/mongo.js
> +  roomId: { type: Schema.Types.ObjectId, ref: "Room"} // 신고한 방 id
어라... prettier가 말썽이네요... 다른 파일도 적용해서 수정해놓았습니다

2023-08-01 13:25 UTC, chlehdwon commented on src/modules/stores/aws.js
> +};
동의해요! 일단 로직 분리해보도록 하겠습니다

2023-08-01 13:31 UTC, 14KGun commented on src/services/reports.js
> +
`required` 로 바꾸로 front와 함께 같이 업데이트 버전 배포하면 좋을 것 같습니다 
(front 코드도 바뀌어야 하기에 숙지하고 있겠습니다)

2023-08-02 03:51 UTC, chlehdwon commented on src/services/reports.js
> +
앗 알겠습니다!! roomId도 required로 수정할게요~!
그렇다면 기존 db migration도 해야 되는 거지요?

2023-08-02 09:04 UTC, 14KGun commented on src/services/reports.js
> +
@chlehdwon 넵넵 마이그레이션 하여도 API 상에서는 `required` 하게 받아야 하니깐 마이그레이션 여부 상관 없이 일단 API에서는 `required`로 받는 것이 좋을 것 같아요

2023-08-02 09:12 UTC, chlehdwon commented on src/services/reports.js
> +
@14KGun 일단 validation 스키마에서 required로 변경 해놓았습니다~! front에서 간단하게 작업하고 dev에서 test해보면 좋을 것 같아요

2023-08-02 17:47 UTC, cokia requested changes

2023-08-02 17:47 UTC, cokia commented on src/modules/slackNotification.js
> +      logger.info("Fail to send slack webhook", err);
logger.error로 수정되면 좋을 듯 합니다!

2023-08-02 17:47 UTC, cokia commented on src/modules/stores/aws.js
> +      logger.info("Fail to send email", err);
마찬가지로 logger.error로 수정되면 좋을 듯 합니다!

2023-08-02 17:59 UTC, 14KGun reviewed
수고하셨습니다.!!! 👍 👍 

마지막 하나만...!! 확인해 주세요 ㅜ

2023-08-02 17:59 UTC, 14KGun commented on src/services/reports.js
> +    const { reportedId, type, etcDetail, time, roomId } = req.body;
@chlehdwon 
`report.save()`에서 

`report`에 `roomId`가 없는 것 같아요!! 😢 

```js
    const room = await roomModel.findById(roomId);
    if (!room) { return res.status(400).json{ ... } }

    const report = new reportModel({
      creatorId,
      reportedId,
      type,
      etcDetail,
      time,
      roomId,
    });

    await report.save();

    notifyToReportChannel(user.nickname, report);

    if (report.type === "no-settlement") {
      const emailRoomName = room ? room.name : "";
      ...
```

제안드려봅니다 !

2023-08-02 18:01 UTC, 14KGun commented on src/services/reports.js
> +    const { reportedId, type, etcDetail, time, roomId } = req.body;
`const room = await roomModel.findById(roomId);`는 `roomId` 의 디비 존재 여부 검증을 위해 `if (report.type === "no-settlement")` 밖에 위치 하는 것이 좋을 것 같아요!! @chlehdwon

2023-08-03 05:06 UTC, chlehdwon commented on src/services/reports.js
> +    const { reportedId, type, etcDetail, time, roomId } = req.body;
핳 이걸 안넣었네요... 수정하겠습니다아...

2023-08-03 05:45 UTC, chlehdwon commented on src/modules/slackNotification.js
> +      logger.info("Fail to send slack webhook", err);
오 고치도록 할게요!! 감사합니다 👍

2023-08-03 07:08 UTC, chlehdwon commented
request에 roomId가 추가됨에 따라 test 코드도 수정하였습니다

2023-08-03 07:20 UTC, 14KGun approved these changes
LYTM 👍

2023-08-05 09:21 UTC, merged