#267 출발전 알림 보내기
sparcs-kaist/taxi-back pull request #306
Opened 2023-05-30 11:30 UTC by ptptsw

# Summary 

It closes #267 

# Images or Screenshots 

 - 출발 15분 전 메시지
 
    <img width="340" alt="스크린샷 2023-09-04 오후 10 51 11" src="https://github.com/sparcs-kaist/taxi-back/assets/69258815/8649ff00-3cce-4c60-ab96-b6191eb8f1f5">

 - 출발 한시간 후 메시지
 
    <img width="340" alt="스크린샷 2023-09-04 오후 10 52 04" src="https://github.com/sparcs-kaist/taxi-back/assets/69258815/42f49b96-faf5-435c-903c-aa25505f2951">

2023-05-30 11:51 UTC, withSang reviewed
우왕 완전 빠르세요!!! 만들어주셔서 감사합니다 :)

2023-05-30 11:51 UTC, withSang commented on src/schedules/notifyBeforeDepart.js
> +  const currentDate = new Date(Date.now() - 15 * MS_PER_MINUTE).toISOString();
여기 +15인 것 같아요!!

2023-06-30 14:35 UTC, ptptsw commented on app.js
> +require("./src/schedules/index")(app.get("io"));
지금 이부분에서 
```
(node:91163) UnhandledPromiseRejectionWarning: ReferenceError: io is not defined
    at /Users/ptptsw/Workspace/taxi-back/src/schedules/notifyBeforeDepart.js:44:25
    at Array.map (<anonymous>)
    at Task.sendReminder [as _execution] (/Users/ptptsw/Workspace/taxi-back/src/schedules/notifyBeforeDepart.js:43:11)
```
에러가 발생하고 있는데, 구글링 해보니까 socket.io instance가 하니라 module handler 형식으로 불러와져서 생기는 문제같아요!
혹시 해결방법을 알고계실까요??

2023-07-01 05:35 UTC, 14KGun commented on app.js
> +require("./src/schedules/index")(app.get("io"));
```suggestion
const io = startSocketServer(serverHttp);
app.set ("io", io);

require ("./src/schedules")(io);
```

왠지 이렇게 코드 바꾸면 해결되지 않을까요(??)

2023-07-01 05:35 UTC, 14KGun commented on app.js
> +require("./src/schedules/index")(app.get("io"));
@ptptsw

2023-07-01 07:04 UTC, ptptsw commented on app.js
> +require("./src/schedules/index")(app.get("io"));
같은 에러 발생해서 좀 더 고민해보겠습니다!!

2023-07-05 14:42 UTC, withSang commented on app.js
> +require("./src/schedules/index")(app.get("io"));
startSocketServer를 promisify 해야할 까요??

2023-07-05 14:54 UTC, withSang commented on src/schedules/notifyBeforeDepart.js
> +      authorId: authorIds[index],
생각해보니까 authorId 사용자에게는 출발 전 알림이 안 가겠군요...! emitChatEvent 구현에 문제가 있어요.. 죄송해요... 😢

2023-07-05 14:54 UTC, 14KGun requested changes
`src/modules/socket.js` 충돌 해결하셔야 할 듯 합니다 !!

2023-07-05 14:54 UTC, 14KGun commented on app.js
> +require("./src/schedules/index")(app.get("io"));
`index.js` 는 생략해도 될듯요

```suggestion
require("./src/schedules")(app.get("io"));
```

2023-07-05 14:54 UTC, 14KGun commented on src/modules/stores/mongo.js
>    authorId: { type: Schema.Types.ObjectId, ref: "User", required: true }, // 작성자 id
지난번 회의에서 `required: true` 없애자고 결론 났던거 같아요

2023-07-05 14:54 UTC, 14KGun commented on src/schedules/notifyBeforeDepart.js
> +      authorId: authorIds[index],
디비 스키마에서 `authorId`의 `required` 옵션 지우고 출발 15분 전 알림이랑 마찬가지로 입퇴장 메시지에서도 `authorId` 지워야 할듯요

2023-07-05 14:55 UTC, 14KGun commented on src/schedules/notifyBeforeDepart.js
> +      authorId: authorIds[index],
이거 고려해서 `emitChatEvent ` 구현도 수정해야 할 듯 합니다.

2023-07-05 15:05 UTC, 14KGun commented on src/schedules/index.js
> +module.exports = registerSchedules;
https://github.com/sparcs-kaist/taxi-back/blob/89bcf6909b205fab6b716880e6b2e6d6b6e52e32/app.js#L63

`app.js` 에서 `io`를 인자로 넘겨주나 함수 정의에 받는 인자가 없습니다 😢

2023-07-05 15:05 UTC, 14KGun commented on src/schedules/notifyBeforeDepart.js
> +    .populate(roomPopulateOption);
방 검색에서 기존에 `출발 15분 전 알림`을 보낸 방이라면, 검색 결과에서 제거되어야 할 것 같아요.

2023-09-03 17:43 UTC, 14KGun commented on app.js
> +require("./src/schedules/index")(app.get("io"));
어떤 구조인지 감이 안잡히는데 코드로 보여주시죠 ㅋㅋㅋ

2023-09-04 08:23 UTC, 14KGun approved these changes

2023-09-04 08:28 UTC, withSang commented on src/services/chats.js
> +    logger.error(e);
👍

2023-09-05 07:11 UTC, withSang commented on src/schedules/index.js
> +  cron.schedule("*/10 * * * *", require("./notifyAfterArrival")(app));
출발 시각을 10분 단위로 설정할 수 있으니까 cron job도 10분에 한 번만 돌리면 되는군요! 좋아보여요 👍

2023-09-05 07:13 UTC, withSang commented on src/schedules/notifyAfterArrival.js
> +            $elemMatch: { settlementStatus: { $nin: ["paid", "sent"] } },
오 not in 연산자가 있군요

2023-09-05 07:18 UTC, withSang commented on src/schedules/notifyBeforeDepart.js
> + * 출발까지 15분 남은 방들에 참여하고 있는 사용자들에게 리마인더 알림을 전송합니다.
코드 기반으로 방의 조건을 추가해도 좋을 것 같습니다!
제가 이해한 건 아래와 같은데 혹시 맞을까요?
```javascript
 * 출발까지 15분 이하가 남았고, 이미 출발 알림이 전송되지 않았으며, 2명 이상이 참여중인 방에 출발 알림을 전송합니다. 
```

2023-09-05 07:25 UTC, withSang approved these changes
좋아 보입니다!!
제가 봄에 끝냈어야 하는 일인데 너무 늦어져서 죄송해요. 대신 끝마쳐주셔서 감사드립니다.

2023-09-08 01:22 UTC, 14KGun commented on src/schedules/notifyBeforeDepart.js
> + * 출발까지 15분 남은 방들에 참여하고 있는 사용자들에게 리마인더 알림을 전송합니다.
@withSang 정확하십니다 :)

2023-09-08 01:23 UTC, 14KGun commented on src/schedules/notifyAfterArrival.js
> +            $elemMatch: { settlementStatus: { $nin: ["paid", "sent"] } },
@withSang 완벽히 이해하셨습니다 ㅋㅋ

2023-09-08 05:15 UTC, 14KGun commented on src/schedules/notifyAfterArrival.js
> +            $elemMatch: { settlementStatus: { $nin: ["paid", "sent"] } },
@withSang 추가 설명 추가 했습니다 :) 확인 부탁드려요

2023-09-08 05:27 UTC, withSang approved these changes

2023-09-08 05:58 UTC, merged