#25 rewrite join disconnect socket events
sparcs-kaist/taxi-back pull request #31
Opened 2022-03-29 13:24 UTC by withSang

Resolves #25

1. 사용자가 처음 방에 들어왔을 때와, 방에서 완전히 나갔을 때에만 입/퇴장 이벤트들을 발생시키도록 수정했습니다.
2. 채팅에서 모든 채팅 내역을 한 번에 보내지 않고, 필요 시 더 보내도록 수정했습니다.
3. 방 생성 API의 response가 제대로 populate되지 않았던 문제를 수정했습니다.

2022-04-05 16:11 UTC, 14KGun requested changes

2022-04-05 16:13 UTC, withSang commented on src/route/rooms.js
> +        text: `${concatenatedNicknames}이 입장했습니다`,
오 분명 나중에 다국어 처리할 때 문제가 생길 것 같습니다. chat에 type 속성("message", "join", "leave" 중 하나를 가지는)을 추가해서 프론트 단에서 텍스트를 생성하는 게 좋을 것 같아요!

2022-04-05 16:14 UTC, withSang commented on src/route/rooms.js
> +      text: `${user.nickname} 님이 퇴장했습니다.`,
수정할 메시지가 두 개 뿐이라 다행인 것 같아요. 좋은 의견 감사합니다!!

2022-04-05 16:20 UTC, 14KGun requested changes

2022-04-05 16:20 UTC, 14KGun commented on src/route/chats.socket.js
> +      io.to(`chatRoom-${roomId}`).emit("chats-receive", { chat });
try catch 필요

2022-04-05 16:52 UTC, withSang commented on src/route/chats.socket.js
> +      io.to(`chatRoom-${roomId}`).emit("chats-receive", { chat });
수정했습니다! 감사합니다 :)

2022-05-24 14:17 UTC, 14KGun approved these changes

2022-05-24 14:18 UTC, merged