#341 2023 가을학기 추석 홍보 이벤트 위한 transactions
sparcs-kaist/taxi-back pull request #364
Opened 2023-09-13 17:48 UTC by kmc7468

# Summary 

It closes #341 
기존 모듈의 services의 일부 API에서 response를 전송하기 직전에 event contracts를 호출하도록 하여 lottery 모듈과 기존 모듈 사이의 결합성은 낮추고, 기존 모듈에서 간단히 이벤트 달성을 구현할 수 있도록 하였습니다.
"방 공유하기", "광고성 푸시 알림 수신 동의", "이벤트 인스타그램 스토리에 공유", "아이템 구매 후 인스타그램 스토리에 공유"는 구현되지 않았습니다. (앱 또는 프론트엔드에서 API 호출 필요하기 때문. 이 부분은 @TaehyeonPark 님이 해주실 예정입니다.)

# Further Work 

- Nothing

2023-09-13 18:15 UTC, kmc7468 commented on src/lottery/index.js
> +const getContract = (name) => {
기존에는 contracts들을 외부에 직접 노출하고, services에서 직접 호출하도록 했습니다. 이렇게 구현한 경우, eventMode가 undefined일 때 lottery/index.js에서 contracts를 불러오지 않기 때문에, 기존 services에서 오류가 발생하는 문제가 있었습니다.

그래서 getContract 함수만 lottery 모듈 외부로 노출하고, string을 통해 contract를 불러오도록 하여 문제를 해결했습니다. 다만 이럴 경우, contract name을 오타낼 수도 있다는 문제점이 있습니다.

더 좋은 구현 방법이 있을까요? 여러분들의 의견을 기다립니다!
+ 항상 꼼꼼한 리뷰 감사드립니다.

2023-09-14 14:38 UTC, cokia requested changes

2023-09-14 16:04 UTC, kmc7468 commented on src/lottery/index.js
> +const getContract = (name) => {
우영님 의견 반영하여 커밋 업로드했습니다. 좋은 의견 감사드립니다!

2023-09-14 16:09 UTC, kmc7468 commented on loadenv.js
> +  },
@withSang 님이 같은 의견을 주셔서, 작업하여 반영한 상태입니다. 의견 감사합니다!

2023-09-14 16:13 UTC, withSang commented on src/lottery/modules/contracts/2023fall.js
> + * @param {*} roomObject
`{*}` 안에 타입 명시해주세요!

2023-09-14 16:14 UTC, withSang commented on src/lottery/modules/contracts/2023fall.js
> + * @param {*} roomObject
`emitChatEvent` 참조하시면 `roomObject`의 각 필드를 어떻게 정의할 수 있는지 보실 수 있어요!

2023-09-14 16:22 UTC, withSang approved these changes
LGTV 📺

2023-09-14 16:22 UTC, withSang commented on src/lottery/modules/events.js
> +    };
return value가 지금은 안 쓰이는 것 같은데 추가하신 이유가 혹시 있을지 궁금해요!

2023-09-14 16:22 UTC, withSang commented on src/modules/adminResource.js
> +  if (!res.response) return res;
오 혹시 추가된 이유가 있나요?

2023-09-15 01:31 UTC, kmc7468 commented on src/modules/adminResource.js
> +  if (!res.response) return res;
현재는 삭제되었지만, 이전에 instagramRewardAction이 존재했을 때 추가된 부분이에요.
Action이 항상 성공하는 것이 아니기 때문에, res.response가 존재하면 성공, 존재하지 않으면 실패로 구분하고자 추가한 코드입니다.

2023-09-15 01:33 UTC, kmc7468 commented on src/lottery/modules/events.js
> +    };
현재는 삭제된 instagramRewardAction 쪽에서 transactionId를 이용하여 Admin Log를 남겼었습니다. 나중에 필요한 일이 있을까봐 반환값은 그대로 유지하였습니다!

2023-09-15 01:48 UTC, kmc7468 commented on src/lottery/modules/contracts/2023fall.js
> + * @param {*} roomObject
감사합니다! 말씀 주신 부분 참고해서 타입 명시 해주었습니다. 혹시 제가 올바르게 작성한 게 맞는지 확인해 주실 수 있을까요?

2023-09-15 04:35 UTC, 14KGun commented on src/services/users.js
> +        : undefined;
`if (contracts) await contracts.requestNicknameChangingEvent(req.userOid);` 아니면
`contracts && await contracts.requestNicknameChangingEvent(req.userOid);` 하시면 될듯합니다

2023-09-15 04:35 UTC, 14KGun commented on src/services/users.js
> +        : undefined;
마찬가지입니다 ~

2023-09-15 04:35 UTC, 14KGun commented on src/services/users.js
> +        : undefined;
흠... `await contracts?.requestNicknameChangingEvent(req.userOid);` 하셔도 될듯요 @kmc7468

2023-09-15 04:35 UTC, 14KGun commented on src/lottery/routes/docs/globalState.js
>                        expireat: {
이거 나중에 `createAt`과 변수명 통일성 맞출 수 있도록 `startAt`, `expireAt` 으로 수정되면 좋을 것 같아요

2023-09-15 04:35 UTC, 14KGun commented on src/lottery/modules/events.js
> +        `eventHandler(userId=${userId}, eventName="${eventName}") 함수에서 예외가 발생했습니다: 알 수 없는 이벤트 이름입니다.`
로거 에러 내용 영어로 구성해주세요!

2023-09-15 04:35 UTC, 14KGun commented on src/lottery/modules/contracts/2023fall.js
> +  // TODO
😄

2023-09-15 04:35 UTC, 14KGun commented on src/lottery/modules/contracts/2023fall.js
> +};
흠...ㅋㅋㅋㅋ 나중에 컨벤션 바꿔서 `module.exports.requestFirstLoginEvent = async () => { ...` 이런식으로 수정되면 더 깔끔할 것 같긴하네요..

@withSang 나중에 타입스크립트 도입할 때에는 `es6` `import` `export` 해주세요 ㅠㅜ

2023-09-15 04:35 UTC, 14KGun commented on src/lottery/index.js
> +  : undefined;
`eventMode` `type`이 `string | undefined` 라면

```suggestion
const constracts = eventMode && require("./module/constracts/${eventMode}");
```

로 바뀌어도 될 것 같군요

2023-09-15 04:35 UTC, 14KGun commented on src/lottery/modules/contracts/2023fall.js
> + *
빈 줄 있어요!

2023-09-15 04:35 UTC, 14KGun commented on src/lottery/modules/contracts/2023fall.js
> +  return await eventHandler(userId, "이벤트 기간 첫 로그인");
이거 이름으로 구분하는 것이 맞을까라는 생각이 드네요... 흠...

퀘스트 리스트는 데이터베이스 컬렉션으로 관리하는 것이 아니라 하나의 JSON 파일로 관리하는 것이 어떨까요??
아 그리고 이제와서 드는 생각인데 `event` 이름은 겹치니깐 `mission` 이나 `quest` 였으면 어떠할까하는 생각이 듭니다.. ㅈㅅ ㅜㅜ @withSang @cokia 

예시 missions.json
```
{
  "missions": [
    {
      "key": string, // unique 한 string example = "requestFirstLogin"
     "name": string, "rewardAmount": number, "maxCount": number ...
    }
  ]
}
```

2023-09-15 04:36 UTC, 14KGun commented on loadenv.js
> +  },
이것을 말하는 거였군 ㅋㅋㅋㅋㅋ

2023-09-15 04:37 UTC, 14KGun requested changes
수고하셨습니다만.. 몇가지 확인해야 할 점이 있는 것 같아요 ㅜ

2023-09-15 06:17 UTC, kmc7468 commented on src/services/users.js
> +        : undefined;
더 깔끔하네요! 좋은 의견 감사합니다. 반영해서 커밋하겠습니다 :)

2023-09-15 06:18 UTC, kmc7468 commented on src/lottery/routes/docs/globalState.js
>                        expireat: {
좋네요! lottery 모듈 안에서는 하나로 통일하는게 좋을 것 같습니다.

2023-09-15 08:20 UTC, 14KGun commented
@kmc7468 

1. 지금 보아하니 `event` 스키마는 필요 없어 보이네요. 디비로 관리될 필요가 없어보이는 이상 `json` 으로 관리되어도 될 것 같아요. 필드에 unique 한 string인 `key` 필즈를 추가하고요.

2. `eventHandler` 이름이 구체적이지 않아 기능을 추측하기 어렵습니다. 핸들러 이름을 `missionCompleteHandler` 추천 드립니다.

3. `eventHandler` 의 반환값이 미션 성공 처리 중 에러가 발생하여도 `null`, 최대 달성 횟수에 도달하여도 `null`을 리턴하네요. 제 생각에 `[err, result]` 를 반환하거나 아니면 `API` 핸들러의 `catch` 로 이동하게끔 핸들러 내부의 `try catch`를 벗겨내는 것도 나쁘지 않아보이네요.  

4. `requestFirstLoginEvent`, `requestPayingAndSendingEvent` 등등 똑같은 패턴의 코드가 반복된다고 생각하는데 이 핸들러들 하나로 통합이 가능해보입니다.

    - `const result: boolean = missionCompleteHandler(userId: string, missionKey: string)` 이런식으로요

2023-09-15 08:21 UTC, kmc7468 commented on src/lottery/index.js
> +  : undefined;
더 짧고 좋네요! 그런데 `constracts` 가 아니라 `contracts` 라서.. ㅠ 제가 로컬에서 직접 수정해서 커밋하도록 하겠습니다. 좋은 의견 감사합니다!

2023-09-15 08:46 UTC, kmc7468 commented
@14KGun 

의견 감사드립니다.

1. 좋은 방법인 것 같습니다. 개인적인 생각으로는, json 파일도 추가로 만들지 않고 contracts에 Event에 대한 모든 정보를 집어 넣는 것도 괜찮을 것 같긴 합니다. 어떻게 생각하시나요?

2. 다음 커밋에서 반영하겠습니다!

3. 이 부분은 제가 예전부터 계속 고민하던 부분이긴 합니다. 예외가 발생했음에도 null을 반환하는 이유는, 결국 택시 서비스의 본질은 택시 동승이지 송편 이벤트가 아니기 때문에, 송편을 지급하는 과정에서 오류가 발생했다고 해서 API 자체에서 오류가 발생한 것으로 처리하지 않으면 좋을 것 같아 저렇게 처리를 해 두었습니다.

4. Event Name 같은 경우에는 (현재 구조에서는) 하드 코딩된 문자열이기 때문에, 한 곳에 모아서 관리하는 것이 좋을 것 같아 contracts를 만들고 eventHandler를 한 번 래핑하는 구조로 기존 모듈의 services 쪽에 제공하고 있습니다. 실제로 services/auth.js와 services/auth.mobile.js 두 파일에서 requestFirstLogin 함수를 호출하고 있는데, 만약 이벤트 이름이 혹시라도 바뀌게 되면 현재 구조에서는 contracts에서만 수정하면 되지만 말씀주신 방법대로 하면 파일 2개를 수정해야 합니다.

2023-09-15 08:54 UTC, 14KGun commented
1. 파일 하나 관리 괜찮은 것 같습니다 ~

3. API를 처리하는 과정 중 서버의 알 수 없는 에러가 Internal server error 입니다!! 이 경우 500의 status code 와 함께 internal server error 반환해 주시면 좋을 것 같습니다 (참고 : https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500)

4. event라는 이름은 택시 송편 **이벤트** 라는 의미로 사용되고 있어 단어 중복이 되는 것 같습니다. 퀘스트는 quest 또는 mission의 단어 선택이 괜찮아보입니다.

2023-09-15 08:56 UTC, 14KGun commented
4. 앗 그럼 제가 나중에 수정된 코드를 봐야 할 것 같아요. 그 때 문제된다면 다시 리뷰하겠습니다ㅜㅜ

2023-09-15 09:27 UTC, kmc7468 commented
2. 제 코멘트의 3번에 답해주신거죠?! 예를 들어 첫 방 생성시 송편 지급하는 경우를 고려해보면, 다른 DB 쿼리는 모두 성공했는데 송편 지급만 실패했으면 기존 쿼리들 모두 롤백해야합니다. 그래서 트랜잭션을 도입하는 것도 괜찮을 것 같은데, 어짜피 아이템 구매에 트랜잭션을 적용하긴 해야해서.. 이 부분은 다른 브랜치를 파서 작업할 생각이긴 합니다. 그럼에도 불구하고 제 개인적인 의견으로는 eventHandler에서의 예외는 밖으로 전파되지 않고 log에 기록되는 선에서 끝났으면 좋을 것 같긴 합니다. 상님과 우영님은 어떻게 생각하시는 지도 궁금해요! @cokia @withSang 

4. 좋네요! 프론트와 맞춰서 Quest로 가면 좋을 것 같아요.

2023-09-15 14:14 UTC, kmc7468 commented on src/lottery/modules/contracts/2023fall.js
> +  // TODO
이 부분은 태현님이 채워주실 예정입니다!

2023-09-16 12:18 UTC, kmc7468 commented on src/lottery/modules/contracts/2023fall.js
> +  return await eventHandler(userId, "이벤트 기간 첫 로그인");
말씀 주신 의견을 반영하여 quest로 변경하였습니다!

2023-09-16 14:35 UTC, kmc7468 commented on src/lottery/routes/docs/globalState.js
>                        expireat: {
startat, expireat 필드는 Quest에서 삭제되었습니다. 대신 contracts/2023fall.js에 정의된 eventPeriod를 참조하여 퀘스트 달성이 가능한 기간인지 검사하도록 변경하였습니다. 추가로, `items/purchase/:itemId` API의 경우에도 해당 변수를 참조해 아이템 구매가 가능한 기간인지 검사하게 됩니다.

만약 문제가 발생하여 이벤트 기간 종료 전에 퀘스트를 비활성화 해야한다면, DB의 Event 콜렉션에 등록하면 됩니다.

2023-09-16 14:37 UTC, kmc7468 commented
저번 리뷰 때 건님이 주신 의견이 대부분 반영되었습니다! 코드가 크게 바뀌어 상님께서도 리뷰를 다시 해주시면 좋을 것 같아요.

여전히 `completeQuest` 발생한 예외는 밖으로 전달되지 않고, `null` 을 반환하는 동작을 유지하고 있습니다. 이 부분은 어떻게 할 지 다음 회의 시간에 논의하고 다른 브랜치에서 작업하면 될 것 같아요!

2023-09-16 18:21 UTC, withSang commented on src/lottery/routes/docs/transactions.js
> +                    required: ["_id", "type", "amount", "comment", "createAt"],
👍

2023-09-16 18:23 UTC, withSang commented on src/lottery/modules/contracts/2023fall.js
> + * @param {*} roomObject
오 정확하게 쓰신 것 같습니다! 감사합니다 👍

2023-09-17 03:12 UTC, 14KGun approved these changes
👍 LGTM 수고하셨습니다 ~

2023-09-17 03:12 UTC, 14KGun commented on src/lottery/modules/quests.js
> +        },
저희 응모권 주는 퀘스트도 있어요!

2023-09-17 04:55 UTC, cokia commented
> 여전히 `completeQuest` 에서 발생한 예외는 밖으로 전달되지 않고, `null` 을 반환하는 동작을 유지하고 있습니다. 이 부분은 어떻게 할 지 다음 회의 시간에 논의하고 다른 브랜치에서 작업하면 될 것 같아요!


코드간 낮은 결합도를 유지하기 위해 이벤트 모듈에서 생긴 예외가 외부에 익셉션으로 직접 안넘어가는게 개인적으로는 이상적인 구현이라고 생각해요 :)

2023-09-17 04:56 UTC, cokia approved these changes
LGMT! 고생하셨습니다 :)

2023-09-17 06:55 UTC, 14KGun requested changes

2023-09-17 06:55 UTC, 14KGun commented on src/lottery/modules/stores/mongo.js
>      type: Number,
음.. 나중에 이벤트 참여 동의 여부도 `eventStatusSchema`에 포함되어 할 것 같습니다.
그리고 동의 하지 않은 사용자들 퀘스트 달성이랑 아이템 구입 막아야 할듯요...

이건 다른 PR에서 하면 좋을 것 같아요

2023-09-17 06:55 UTC, 14KGun commented on src/services/auth.js
> +    await contracts?.completeFirstLoginQuest(user._id);
이거 세션 만료가 2주였나 엄청 길어서..
로그인 체크 여부는 auth 미들웨어에서 해야할 것 같아요

2023-09-17 06:55 UTC, 14KGun commented on src/services/auth.mobile.js
> +    await contracts?.completeFirstLoginQuest(user._id);
auth 미들웨어에서 하면 이 코드도 지워도 되구요

2023-09-17 07:28 UTC, kmc7468 commented on src/lottery/modules/quests.js
> +    }
questDoc이 null일 때는 오류가 아닙니다! DB에는 모든 Quest가 올라가는 것이 아니라, 비활성화 할 Quest만 저장하도록 할 예정이에요.

2023-09-17 07:30 UTC, kmc7468 commented on src/lottery/modules/quests.js
> +        },
아 맞다! 현재 구조상 송편 외에 다른 것을 지급할 방법이 없어서 응모권 1개에 해당하는 송편을 지급한 후 바로 아이템 구매를 하도록 만들 생각이었는데 반영을 못했네요.

까먹을 뻔 했네요 알려주셔서 감사합니다 ㅎㅎ

2023-09-17 08:24 UTC, kmc7468 commented on src/lottery/modules/contracts/2023fall.js
> +};
그런 경우는 생각하지 못했네요! 알려주셔서 감사합니당

2023-09-17 08:25 UTC, kmc7468 commented on src/services/auth.js
> +    await contracts?.completeFirstLoginQuest(user._id);
Slack에서 이야기 나눈대로, 다른 브랜치에서 이벤트 참여 동의 받는 부분 구현 후 그곳에서 completeFirstLoginQuest 함수 호출하도록 하는걸로 하겠습니다.

2023-09-17 15:02 UTC, 14KGun commented on src/services/auth.js
> +    await contracts?.completeFirstLoginQuest(user._id);
좋습니다 ~ 👍

2023-09-17 15:03 UTC, 14KGun commented on src/lottery/modules/quests.js
> +    }
아 그렇군요 ㅎ 설명해주셔서 감사합니다 !

2023-09-17 15:06 UTC, 14KGun commented on src/lottery/modules/stores/mongo.js
>      type: Number,
https://github.com/sparcs-kaist/taxi-back/issues/372

이슈 만들었습니다 ~

2023-09-17 16:11 UTC, kmc7468 commented on src/lottery/modules/quests.js
> +        },
퀘스트에서 완료 보상으로 응모권을 지급할 수 있도록 변경하였습니다!

2023-09-17 16:41 UTC, 14KGun approved these changes
좋아 보입니다!!
고생 하셨습니다 ~~ 😄 👍

2023-09-17 16:42 UTC, merged