#361 public notice
sparcs-kaist/taxi-back pull request #370
Opened 2023-09-16 14:04 UTC by TaehyeonPark

# Summary 
인스타그램 이벤트에 해당하는 작업과 공지문구가 합쳐져있습니다.
It closes #issue_number
#361 #360 
# Extra info 
n
# Images or Screenshots 

# Further Work 

- Do something...

2023-09-17 17:03 UTC, kmc7468 commented
dev 쪽 변경사항이 많아서 충돌이 발생하네요..! 충돌 해결이 필요할 것 같습니다.

그리고 Transaction의 comment 형식이 변경되었어요. 파싱이 좀 더 어려워진 것 같긴 한데.. 이 부분 반영해 주실 필요가 있어 보입니다 ㅠㅠ

2023-09-18 14:52 UTC, kmc7468 commented on src/lottery/modules/populates/publicNotice.js
transaction document를 populate 하는거니까 transactions.js에 populate option이 있어야 하지 않을까요?

2023-09-18 14:53 UTC, kmc7468 commented on src/lottery/modules/populates/publicNotice.js
그래서 사실 이미 populates/transactions.js가 있기 때문에 이 파일은 굳이 필요가 없을 것 같습니다.

2023-09-18 14:54 UTC, kmc7468 commented on src/lottery/routes/quests.js
> +router.use(require("../../middlewares/auth"));
auth middleware 가져오는 부분이랑 endpoint 정의하는 부분 사이에 빈 줄 하나 있으면 좋을 것 같아요.

2023-09-18 15:13 UTC, TaehyeonPark commented on src/lottery/services/publicNotice.js
> +      .lean();
시간, 송편을 파라미터로 하는 가치 함수를 넣어 정렬하는 것이 좋을 것 같다

2023-09-18 15:13 UTC, TaehyeonPark commented on src/lottery/services/publicNotice.js
> +  return transactions;
DB 쿼리 검색으로 성능 개선이 가능할 것 같아요

2023-09-18 15:13 UTC, TaehyeonPark commented on src/lottery/services/publicNotice.js
> +const getTransactions = async () => {
함수 이름이 추상적인 것 같다. 더 구체적으로 적으면 어떠할까요

2023-09-18 15:13 UTC, TaehyeonPark commented on src/lottery/services/quests.js
> +    const userId = req.userOid;
컨벤션 룰에 따라서 `const { userOid: userId } = req;`

로 es6 문법 쓰면 좋을 것 같습니다.

2023-09-18 15:13 UTC, TaehyeonPark commented on src/lottery/services/quests.js
> +    res.json({ result: !!contractResult ? true : false });
이거 `res.json({ result: !!contractResult });` 랑 똑같지 않나요?

2023-09-18 15:13 UTC, TaehyeonPark commented on src/lottery/services/quests.js
> +    res.json({ result: !!contractResult ? true : false });
위랑 리뷰 동일 입니다.

2023-09-18 15:13 UTC, TaehyeonPark commented on src/lottery/services/quests.js
> +    const userId = req.userOid;
리뷰 동일 입니다.

2023-09-18 15:37 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +const getRecentTransaction = async (req, res) => {
컨벤션에 따라 함수 이름 뒤에 Handler 붙여주시면 좋을 것 같습니다.

2023-09-18 15:37 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +    if (!!transactions) {
여기서 !!는 없어져도 될 것 같습니다.

2023-09-18 15:39 UTC, kmc7468 commented on src/lottery/services/quests.js
> +    res.status(500).json({ error: "Quests/Insagram/Share-Purchase" });
오타있습니다!! `Quests/Instagram/ShareEvent` 로 바꿔야 할 것 같아요. 그리고 다른 것처럼 `: internal server error` 붙여주셔야 합니다.

2023-09-18 15:39 UTC, kmc7468 commented on src/lottery/services/quests.js
> +    res.status(500).json({ error: "Quests/Insagram/Share-Event" });
오타있습니다!! `Quests/Instagram/ShareEvent` 로 바꿔야 할 것 같아요. 그리고 다른 것처럼 `: internal server error` 붙여주셔야 합니다.

2023-09-18 15:47 UTC, kmc7468 commented on src/lottery/routes/docs/swaggerDocs.js
> +const eventsDocs = require("./events");
quests로 이름 변경 필요할 것 같습니다!

2023-09-18 15:48 UTC, kmc7468 commented on src/lottery/routes/docs/swaggerDocs.js
>      {
public-notice가 2개 있는 것 같아요!

2023-09-18 15:49 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +      .sort({ doneat: -1 })
doneat은 createAt으로 이름 바뀌었습니다!

2023-09-18 17:25 UTC, withSang reviewed
개발 빠르시네요.. 고생하셨합니다!

2023-09-18 17:25 UTC, withSang commented on src/lottery/modules/populates/publicNotice.js
저도 말씀하신 바와 같이 생각해요!

2023-09-18 17:25 UTC, withSang commented on src/lottery/routes/docs/events.js
> +eventsDocs[`${apiPrefix}/share-event`] = {
camel case로 바꿔주세요!

2023-09-19 07:40 UTC, kmc7468 commented on src/lottery/routes/docs/events.js
> +const apiPrefix = `/events/${eventMode}/instagram`;
apiPrefix도 수정이 필요할 것 같습니다. Path가 `/events/2023fall/quests`로 시작하면 quests.js에 있는 라우터가 호출(?)되기 때문에, `/events/${eventMode}/quests` 로 바꿔주는게 좋을 것 같아요.

2023-09-19 07:41 UTC, kmc7468 commented on src/lottery/routes/docs/events.js
> +eventsDocs[`${apiPrefix}/share-event`] = {
apiPrefix를 제가 제안 드린 것처럼 수정하면, 여기선 `${apiPrefix}/instagram/share-event` 로 바뀌어야 할거예요.

2023-09-19 07:41 UTC, kmc7468 commented on src/lottery/routes/docs/events.js
> +eventsDocs[`${apiPrefix}/share-purchase`] = {
apiPrefix를 제가 제안 드린 것처럼 수정하면, 여기선 `${apiPrefix}/instagram/share-purchase` 로 바뀌어야 할거예요.

2023-09-19 07:42 UTC, kmc7468 commented on src/lottery/routes/docs/events.js
> +      500: { error: "Events/Insagram/Share-Purchase" },
500은 저희 보통 문서화하지 않긴 합니다! 만약 문서화 하실거라면 오타 수정 및 네이밍 컨벤션 수정이 필요할 것 같아요.

2023-09-19 07:43 UTC, kmc7468 commented on src/lottery/routes/docs/swaggerDocs.js
> +      name: `${apiPrefix}/instagram`,
제가 위에서 말씀드린 코멘트가 반영되면 이곳에서는 `${apiPrefix}/quests` 로 바뀌어야 합니다.

2023-09-19 07:44 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +        if (item.comment.includes("구매")) {
여긴 제안이 아니라 질문 드리는건데, `comment` 형식 변경된 것 반영된 코드인걸까요?!

2023-09-19 12:13 UTC, TaehyeonPark commented on src/lottery/services/publicNotice.js
> +    if (!!transactions) {
> 여기서 !!는 없어져도 될 것 같습니다.

코드가 바뀌어서 다시 확인해주시면 감사합니다!

2023-09-19 12:17 UTC, TaehyeonPark commented on src/lottery/services/publicNotice.js
> +      .lean();
> 시간, 송편을 파라미터로 하는 가치 함수를 넣어 정렬하는 것이 좋을 것 같다

이를 구현하기 위해서 스키마 구조가 바뀌었습니다. 만약 구현을 하게 된다면 로직이 복잡해질 가능성이 있습니다. 확인 부탁드립니다!

2023-09-19 12:40 UTC, TaehyeonPark commented on src/lottery/routes/docs/events.js
> +      500: { error: "Events/Insagram/Share-Purchase" },
> 500은 저희 보통 문서화하지 않긴 합니다! 만약 문서화 하실거라면 다른 코멘트에서 말씀드린 것과 똑같은 형식으로 수정해 주셔야 할 것 같아요.

해당 사항은 삭제 조치 반영했습니다!

2023-09-19 13:27 UTC, kmc7468 commented on src/lottery/modules/contracts/2023fall.js
> +const completeEventSharingOnInstagramQuest = async (userId) => {
JSDoc 달아주셔야 해요! 위에 있는 다른 함수들 참고해서 작성해 주시면 될 것 같아요.

2023-09-19 13:27 UTC, kmc7468 commented on src/lottery/modules/contracts/2023fall.js
>  const completePurchaseSharingOnInstagramQuest = async () => {
여기도 JSDoc 필요합니다.

2023-09-19 13:29 UTC, kmc7468 commented on src/lottery/modules/populates/publicNotice.js
populates/transactions.js와 통합되는게 좋을 것 같아요!

2023-09-19 13:29 UTC, kmc7468 commented on src/lottery/modules/populates/publicNotice.js
> +    select: "name price description itemType",
itemType은 select 안해도 되지 않을까요? Transaction에 이미 포함되어 있으니까요!

2023-09-19 13:34 UTC, kmc7468 requested changes

2023-09-19 13:34 UTC, kmc7468 commented on src/lottery/routes/docs/quests.js
> +            schema: {
```
schema: {
  type: "object",
  required: ["result"],
  properties: {
    result: {
      type: "boolean",
      example: true,
    }
  }
}
```

이런 식으로 해주셔야 해요! description 넣는 것도 잊지 말아주시구요!

2023-09-19 13:34 UTC, kmc7468 commented on src/lottery/routes/docs/quests.js
> +            schema: {
위와 코멘트와 내용 동일합니다.

2023-09-19 13:34 UTC, kmc7468 commented on src/lottery/routes/docs/swaggerDocs.js
> +      name: `${apiPrefix}/instagram`,
이거 instagram에서 quests로 수정되어야 합니다.

2023-09-19 13:34 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +    if (!!transactions) {
`!!` 아직 안사라진 것 같아요..!

2023-09-19 13:34 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +        error: "PublicNotice/get-recent-transaction : internal server error",
get-recent-transaction은 PascalCase로 수정 부탁드립니다! `GetRecentTransaction` 같은 느낌으루요.

2023-09-19 13:34 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +      error: "PublicNotice/get-recent-transaction : internal server error",
위와 리뷰 동일합니다.

2023-09-19 14:14 UTC, kmc7468 commented on src/lottery/modules/contracts/2023fall.js
> + * @usage users/editAccountHandler
수정이 안됐습니다!

2023-09-19 14:15 UTC, kmc7468 commented on src/lottery/modules/contracts/2023fall.js
> + * @usage users/editAccountHandler
여기도 수정 부탁드립니다!

2023-09-19 14:17 UTC, kmc7468 commented on src/lottery/routes/docs/quests.js
> +                  example: true,
여기 description 추가 부탁드려요! `description: "성공 여부. 항상 true입니다."` 로 하면 될 것 같습니다.

2023-09-19 14:17 UTC, kmc7468 commented on src/lottery/routes/docs/quests.js
> +                  example: true,
description 추가 부탁드립니다! 내용은 위 코멘트와 같습니다.

2023-09-19 14:18 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +        error: "PublicNotice/RecentTransaction : internal server error",
Transactions로 수정 부탁드려요!

2023-09-19 14:25 UTC, withSang commented on src/lottery/modules/contracts/2023fall.js
> + * @usage rooms - createHandler
👍

2023-09-19 14:27 UTC, kmc7468 commented on src/lottery/modules/populates/transactions.js
> +const publicNoticePopulateOption = [
`transactionPopulateOptionWithUserId` 같은 이름은 어떤가요? 너무 장황해지는 것 같긴한데.. transactions을 populate 한다는 의도가 이름에 담겨있으면 좋을 것 같아요. 별로면 그냥 무시하셔도 됩니다!

2023-09-19 14:28 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> -
여기 빈 줄 하나 없어졌어요..!

2023-09-19 14:31 UTC, withSang commented on src/lottery/services/publicNotice.js
> +const returnAnonymousedNickname = (nickname) => {
`deidentifyNickname`은 어떨까요? (return은 함수라는 것에서 이미 의미가 드러나니까 표기 안하셔도 괜찮을 것 같아요!)
아니면 `hideNickname`도 괜찮을 것 같아요.

2023-09-19 14:47 UTC, kmc7468 commented on src/lottery/routes/docs/publicNotice.js
> +(publicNoticeDocs[`${apiPrefix}/recentTransactions`] = {
소괄호 지워주세용!

2023-09-19 14:48 UTC, kmc7468 commented on src/lottery/routes/docs/publicNotice.js
> +}),
여기 세미콜론이 아니라 콜론으로 되어있네요..!

2023-09-19 14:48 UTC, kmc7468 commented on src/lottery/routes/docs/publicNotice.js
> +  (publicNoticeDocs[`${apiPrefix}/leaderboard`] = {
여기도..

2023-09-19 14:49 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +      .find({ type: "use" })
쿼리에 `itemType: 0` 들어가야 되지 않나요?

2023-09-19 14:50 UTC, TaehyeonPark commented on src/lottery/routes/docs/publicNotice.js
> +}),
프리티어가 ,을 끝나지 않는걸로 인식해서 ()을 자동으로 씌워줬네요

2023-09-19 15:06 UTC, kmc7468 commented on src/lottery/routes/docs/publicNotice.js
> +              items: ["string"],
```
items: {
  type: "string"
}
```
이렇게 해야할겁니다!

2023-09-19 15:13 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +        transactionListString,
transactions: ~~~ 로 해주심 될 것 같아요.

2023-09-19 15:21 UTC, kmc7468 approved these changes
너무 수고하셨습니다..!!!

2023-09-19 16:06 UTC, 14KGun commented on src/lottery/services/publicNotice.js
> +    }
```suggestion
    const transactions = await transactionModel
      .find({ type: "use", itemType: 0 })
      .sort({ createAt: -1 })
      .limit(5)
      .populate(publicNoticePopulateOption)
      .lean()
      .map(({ userId, item, comment }) => `${hideNickname(
          userId.nickname
        )}님께서 ${item.item.name}을(를) ${comment.startsWith("송편") ? "어쩌구저쩌구" : comment.startsWith("랜덤 박스") ? "어쩌구" : "저쩌구"}`);
```

2023-09-19 16:33 UTC, TaehyeonPark reviewed
LGTM!

2023-09-19 16:35 UTC, 14KGun approved these changes
LGTM!

2023-09-19 16:35 UTC, merged