#372 이벤트 참여 동의 여부 확인
sparcs-kaist/taxi-back pull request #373
Opened 2023-09-18 04:43 UTC by kmc7468

# Summary 

It closes #372 
새롭게 추가된 `/global-state/create` API를 통해 eventStatus를 생성할 수 있습니다.

# Extra info 
- eventStatus가 생성되면 자동으로 firstLoginQuest가 완료되고 보상이 지급됩니다.
- eventStatus가 생성되기 전 `/global-state` API를 호출하면 400 BAD REQUEST 오류가 발생합니다. 오류 메시지: `GlobalState/ : nonexistent eventStatus`
- eventStatus가 생성되기 전 생성되기 전 `/items/purchase/:itemId` API를 호출하면 400 BAD REQUEST 오류가 발생합니다. 오류 메시지: `Items/Purchase : nonexistent eventStatus`
- `completeQuest` 함수에서는 eventStatus가 존재하지 않는 경우 아무 로그도 남기지 않고 종료됩니다.

# Images or Screenshots 

# Further Work 

- #365

2023-09-18 05:29 UTC, 14KGun requested changes

2023-09-18 05:29 UTC, 14KGun commented on src/lottery/services/globalState.js
> +        .json({ error: "GlobalState/ : nonexistent eventStatus" });
이벤트 참여 동의를 하지 않은 사용자에게 400 에러를 반환하면 안됩니다.

global-state API에 퀘스트 리스트가 포함되어 있는데,
400에러를 반환하면 퀘스트 리스트를 동의 하지 않은 사용자는 퀘스트 리스트를 확인 할 수 없습니다.

이거 동의 여부 response에 새로 필드 하나 만들어서 `boolean` 값으로 넘겨 주실 수 있나요??

2023-09-18 06:06 UTC, kmc7468 commented on src/lottery/services/globalState.js
> +        .json({ error: "GlobalState/ : nonexistent eventStatus" });
아 그렇네요! 그러면 agreement 필드에 동의 여부를(사실은 EventStatus의 존재 여부를) 넣어드리고, false인 경우에는 creditAmount 등 다른 필드의 값은 0 또는 []를 넣어 반환하도록 하겠습니다.

2023-09-18 06:26 UTC, withSang commented on src/lottery/services/globalState.js
> +const createUserGlobalStateHandler = async (req, res) => {
기존 이용약관 동의 핸들러(`agreeOnTermsOfService`)와 일관성을 맞추기 위해 `agreeOnTermsOfEvent`는 어떨까요?

2023-09-18 06:29 UTC, withSang commented on src/lottery/services/items.js
>      const now = Date.now();
Date.now()를 직접 사용하는 대신 `middlewares/informaton.js`에서 설정되는 `req.timestamp` 값을 써주세요!
(유닛 테스트 환경에서는 Date.now()의 값이 테스트 때마다 달라집니다).

2023-09-18 06:30 UTC, kmc7468 commented on src/lottery/services/globalState.js
> +const createUserGlobalStateHandler = async (req, res) => {
좋아요! 그러면 API의 Path를 조금 바꾸는게 좋을 것 같습니다. `/global-state/agreeOnTermsOfEvent` 는 조금 이상한 것 같아서요. 어떤 것이 좋을까요?

2023-09-18 06:32 UTC, withSang commented on src/lottery/services/items.js
>      if (!item)
이번 PR에서 다뤄지지는 않은 거지만.. `purchaseHandler`가 URL param으로 받는 itemId에는 입력값 검증이 필요합니다! reports 쪽 라우터 참조하시면 ajv를 사용해 입력값 검증이 가능하실 거예요.

2023-09-18 06:37 UTC, withSang commented on src/lottery/services/globalState.js
> +const createUserGlobalStateHandler = async (req, res) => {
기존 이용약관 동의가 `/users/agreeOnTermsOfService` URL을 통해 호출되는 것을 고려하면 `/events/2023fall/users/agreeOnTermsOfEvent` 도 괜찮다고 생각해요!

2023-09-18 06:38 UTC, withSang requested changes
몇 가지 제안드립니다. 감사합니다!

2023-09-18 06:54 UTC, kmc7468 commented on src/lottery/services/items.js
>      if (!item)
의견 감사합니다! lottery 모듈의 작업이 거의 마무리 될 즈음에 PR을 하나 만들어서 모든 API에 validator를 붙일 생각을 하고 있었습니다. 사실 작업이 거의 마무리 되어 가고 있는 듯 해서, public-notice 관련해서 태현님이 PR 열으신게 dev로 머지된 후 작업하면 될 것 같습니다.

2023-09-18 07:07 UTC, withSang commented on src/lottery/services/items.js
>      if (!item)
그렇군요 ㅎㅎ 지금 당장은 이벤트 쪽 api 중에 입력값을 받는 게 아이템 구매 밖에 없어서, 이번 pr에서 작업해두시면 좋을 듯 합니다!

2023-09-18 08:33 UTC, kmc7468 commented on src/lottery/services/items.js
>      if (!item)
생각해보니 그렇네요! 알려주셔서 감사합니다. 다음 커밋에서 반영하겠습니다.

2023-09-18 08:33 UTC, kmc7468 commented on src/lottery/services/items.js
>      const now = Date.now();
의견 감사합니다! 반영했습니다. `completeQuest` 쪽에서도 가능하면 `req.timestamp` 를 가져다 쓰도록 개선했어요.

2023-09-18 10:37 UTC, kmc7468 commented on src/lottery/services/items.js
>      if (!item)
express-validator에 있는 param 함수를 이용하여 구현 완료했습니다.

2023-09-18 10:38 UTC, kmc7468 commented on src/lottery/services/globalState.js
> +const createUserGlobalStateHandler = async (req, res) => {
흠, Router가 너무 많아지는 것 같아서 개인적으로는 현재 방식을 유지하는 것도 나쁘지 않을 것 같긴 합니다!

2023-09-18 12:33 UTC, 14KGun requested changes

2023-09-18 12:33 UTC, 14KGun commented on src/lottery/routes/docs/globalState.js
> +                "agreement",
boolean 변수의 경우 컨벤션에 따라 변수명이 `is` 로 시작하면 좋을 것 같아요

2023-09-18 12:33 UTC, 14KGun commented on src/lottery/routes/items.js
> +  param("itemId").isMongoId(),
잉 저희 `ajv validator` 써야 하지 않나요???

2023-09-18 12:33 UTC, 14KGun commented on src/lottery/routes/globalState.js
>  router.use(require("../../middlewares/auth"));
로그인 하지 않은 사용자도 퀘스트 리스트 확인할 수 있게 `auth`미들웨어 `getUserGlobalStateHandler` 에서는 분리하면 좋을 것 같네요

2023-09-18 12:36 UTC, kmc7468 commented on src/lottery/routes/globalState.js
>  router.use(require("../../middlewares/auth"));
그럼 globalState API도 leaderboard API와 비슷하게 로그인 되지 않은 경우 `quests` 필드만, 로그인 된 경우에는 모든 필드를 제공하도록 변경하겠습니다.

2023-09-18 12:37 UTC, kmc7468 commented on src/lottery/routes/items.js
> +  param("itemId").isMongoId(),
음.. `users.js` 같은 곳을 보면 express-validator를 사용하고 있긴 하더라고요. `ajv validator` 를 사용해야 할까요?

2023-09-18 12:37 UTC, kmc7468 commented on src/lottery/routes/docs/globalState.js
> +                "agreement",
앗 그렇네요! 빠르게 수정하도록 하겠습니다.

2023-09-18 13:27 UTC, kmc7468 commented on src/lottery/routes/docs/globalState.js
> +                "agreement",
`isAgree` 로 변경되었습니다. 감사합니다!

2023-09-18 13:28 UTC, kmc7468 commented on src/lottery/routes/globalState.js
>  router.use(require("../../middlewares/auth"));
로그인 되지 않은 경우/이벤트 참여에 동의하지 않은 경우 모두 globalState에 접근 가능하게 됐으며, 이 경우 quests 필드에는 전체 퀘스트 목록이, 나머지 필드에는 기본값(0 또는 [])이 담겨집니다. 이벤트 참여에 동의한 경우 모든 필드가 적절히 채워지게 됩니다.

2023-09-18 14:41 UTC, kmc7468 commented on src/lottery/routes/items.js
> +  param("itemId").isMongoId(),
반영했습니다!

2023-09-18 16:09 UTC, 14KGun commented on src/lottery/routes/globalState.js
> +router.post("/create", auth, globalStateHandlers.createUserGlobalStateHandler);
`auth` 미들웨어를 라우터 내부에 넣는 형태가 아닌 로그인이 필요한 API가 하단, 로그인이 필요 없는 API가 하단에 위치하도록 코드 구성하면 좋을 것 같습니다.

```suggestion

router.get("/", globalStateHandlers.getUserGlobalStateHandler);

// 라우터 접근 시 로그인 필요
router.use(require("../../middlewares/auth"));
router.post("/create", globalStateHandlers.createUserGlobalStateHandler);
```

2023-09-18 16:09 UTC, 14KGun commented on src/lottery/routes/items.js
> +);
위 리뷰와 동일

2023-09-18 16:09 UTC, 14KGun commented on src/lottery/services/globalState.js
> +    res.json(result);
```suggestion
    const userId = isLogin(req) ? getLoginInfo(req).oid : null;
    const eventStatus = userId && await eventStatusModel.findOne({ userId }).lean();
    if (eventStatus) {
      return res.json({
        isAgree: true,
        creditAmount: eventStatus.creditAmount,
        completedQuests: eventStatus.completedQuests,
        ticket1Amount: eventStatus.ticket1Amount,
        ticket2Amount: eventStatus.ticket2Amount,
        quests,
      });
    }
    res.json({
      isAgree: false,
      creditAmount: 0,
      completedQuests: [],
      ticket1Amount: 0,
      ticket2Amount: 0,
      quests,
    });
```

2023-09-18 17:09 UTC, withSang commented on src/lottery/modules/contracts/2023fall.js
> -  nicknameChaning: {
ㅗㅜㅑ...

2023-09-18 17:10 UTC, withSang commented on src/lottery/modules/contracts/2023fall.js
> + * @param {Date} timestamp - 퀘스트 완료를 요청한 시각입니다.
req.timestamp 를 설정해주는 `information` 미들웨어를 사용해주세요!

2023-09-18 17:12 UTC, withSang commented on src/lottery/modules/contracts/2023fall.js
> + * @param {Date} timestamp - 퀘스트 완료를 요청한 시각입니다.
아 맞다 Date.now()의 타입은 `Date`가 아니라 `Number`입니다.

2023-09-18 17:32 UTC, kmc7468 commented on src/lottery/modules/contracts/2023fall.js
> + * @param {Date} timestamp - 퀘스트 완료를 요청한 시각입니다.
1. completeQuest 함수를 호출하는 곳에서 timestamp 파라미터를 `req.timestamp` 를 이용해 채우도록 구현해 두었습니다!

2. 와.. 충격적이네요. 알려주셔서 감사합니다! 다음 커밋에서 수정할게요.

2023-09-18 17:35 UTC, kmc7468 commented on src/lottery/routes/docs/globalState.js
> +                isAgree: {
좋아요! `is` 로 시작하자는 건님 의견과 합쳐서(?) `isAgreeOnTermsOfEvent` 로 이름을 바꾸도록 하겠습니다. 어떤 의미를 갖는 필드인지 더 명확하게 이해할 수 있을 것 같아서 좋네요!

2023-09-18 18:00 UTC, withSang approved these changes
좋아 보입니다! 감사합니다 👍

2023-09-19 04:05 UTC, 14KGun approved these changes
고생하셨습니다 ~~~ 👍 👍

2023-09-19 04:05 UTC, 14KGun commented on src/lottery/modules/contracts/2023fall.js
> -  nicknameChaning: {
ㅋ

2023-09-19 05:34 UTC, merged