Add: getValueRank evaluate the rank of public notice
sparcs-kaist/taxi-back pull request #385
Opened 2023-09-20 15:46 UTC by TaehyeonPark

# Summary 

#378-public-notice-value-rank
public notice의 순위를 결정하는 가치 판단 함수

# Extra info 
n
# Images or Screenshots 
n
# Further Work 
n
- Do something...

2023-09-20 16:02 UTC, withSang requested changes
가치함수에 대해 논의됐던 대로 잘 짜신 것 같습니다! 몇 가지 제안사항을 드립니다. 감사합니다!

2023-09-20 16:02 UTC, withSang commented on src/lottery/services/publicNotice.js
> +};
계산식에 대한 설명을 추가해두시면 미래에 해당 식을 다시 사용할 때 도움이 됩니다!
예시) 
- getValueRank는 사용자의 상품 구매 내역 또는 경품 추첨 내역의 가치를 평가하는 함수임
- 상품 구매/평품 추첨 시각과 현재 시각의 차이가 작을수록 가치가 높음
- 구매한 상품/당첨된 경품 가격에 비례하여 가치는 높아짐
- 사용 시에는 최근 구매 내역을 valueRank를 기준으로 내림차순 정렬함

2023-09-20 16:02 UTC, withSang commented on src/lottery/services/publicNotice.js
> +};
slice(7,10)을 적용할 때 저희가 가치함수를 세울 때 의도(최근 구매 내역이 더 높은 가치를 가짐)에 벗어나는 결과가 나오지 않는지도 논리적인 확인이 필요합니다.

2023-09-20 16:06 UTC, kmc7468 requested changes
수고하셨습니다! 코멘트 확인 부탁드려요~~

2023-09-20 16:06 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +        .limit(1000)
준비된 상품 개수가 그렇게 많지 않아서 limit은 그냥 아예 지워버려도 좋을 것 같아요.

2023-09-20 16:06 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
>          .sort({ createAt: -1 })
sort도 필요 없을 것 같아요. 어짜피 밑에서 정렬을 하니까요!

2023-09-20 16:06 UTC, kmc7468 commented on src/lottery/services/publicNotice.js
> +      (new Date(createAt).getTime() / timestamp).toString().slice(7, 10)
알고리즘의 의도 파악이 잘 안되는데, 주석을 달아주시면 더 좋을 것 같아요.

그리고 number -> string -> number는 조금 비효율적일 것 같은데, `Math.floor` 를 잘 응용하면 형 변환 없이 구현 가능할 것 같기도 합니다.

2023-09-20 16:09 UTC, withSang commented
다른 pr처럼 이슈 연결해주시면 됩니다!
(`It resolves #378` 추가)

2023-09-20 16:24 UTC, withSang commented on src/lottery/services/publicNotice.js
> +};
일반적으로 시간에 따라 변하는 가치를 평가할 때 많이 쓰이는 exponential decay를 적용해도 괜찮을 것 같아요 ㅎㅎ
상품 가격 스케일(수백 송편)에 맞춰서 rate constant만 잘 설정하면 되지 않을까 생각해봅니다.
참조: wikipedia - exponential decay https://en.m.wikipedia.org/wiki/Exponential_decay

2023-09-21 07:05 UTC, TaehyeonPark commented on src/lottery/services/publicNotice.js
>          .sort({ createAt: -1 })
limit 현재는 1000으로 걸려 있어서 엣지 케이스는 없겠지만, 최근 순에서 다시 정렬하는 것이기 때문에 sort는 필요합니다!

2023-09-21 19:17 UTC, 14KGun commented on src/lottery/services/publicNotice.js
> +          }`
text 정보 뿐만 아니라 시간 정보도 함께 넘겨주세요 !

2023-09-21 19:23 UTC, withSang commented on src/lottery/services/publicNotice.js
> +          }`
`taxi-back`에서 사용중인 date 라이브러리가 없어서, 이번에 taxi-front에서 사용하는 [day.js](https://day.js.org/docs/en/display/format)를 도입해주셔도 좋아요! @TaehyeonPark

2023-09-22 12:04 UTC, TaehyeonPark commented on src/lottery/services/publicNotice.js
> +        .limit(1000)
최근 데이터만 가져오기 위해서 넉넉하게 1000으로 잡아놨습니다!

2023-09-22 15:00 UTC, TaehyeonPark commented on src/lottery/services/publicNotice.js
> +      (new Date(createAt).getTime() / timestamp).toString().slice(7, 10)
정상님 코멘트 참고해서 새로 만들었습니다!

2023-09-22 15:23 UTC, TaehyeonPark commented on src/lottery/services/publicNotice.js
> +};
comment 감사합니다! 참고해서 좋은 코드가 탄생했습니다!

> 일반적으로 시간에 따라 변하는 가치를 평가할 때 많이 쓰이는 exponential decay를 적용해도 괜찮을 것 같아요 ㅎㅎ 상품 가격 스케일(수백 송편)에 맞춰서 rate constant만 잘 설정하면 되지 않을까 생각해봅니다. 참조: wikipedia - exponential decay https://en.m.wikipedia.org/wiki/Exponential_decay

2023-09-22 15:43 UTC, kmc7468 approved these changes
수고하셨습니다!

2023-09-22 19:18 UTC, withSang commented on src/lottery/services/publicNotice.js
> + * @param {number|Date} timestamp
이 두개는 number입니다!

2023-09-22 19:20 UTC, withSang commented on src/lottery/services/publicNotice.js
> + * @param {number|Date} timestamp
앗 createdAt은 무조건 Date이고, `timestamp`는 무조건 Number입니다!

2023-09-22 19:21 UTC, withSang approved these changes
오 너무 좋은 것 같습니다!! 메인 코드 반영되는 데 전혀 문제가 없을 것 같습니다.
늦은 시간까지 고생 많으셨어요!

2023-09-22 21:07 UTC, 14KGun approved these changes
LGTM! 👍

2023-09-22 21:34 UTC, 14KGun commented on src/lottery/services/publicNotice.js
>              ? "을(를) 뽑았습니다."
@TaehyeonPark front-end랑 지금까지 디자인에서 "뽑았습니다" 라는 텍스트를 안쓰는데,
혹시 "획득하셨습니다." 라고 텍스트 수정하는 것 어떠신가요?

2023-09-22 21:34 UTC, 14KGun commented on src/lottery/services/publicNotice.js
>              ? "을(를) 뽑았습니다."
이거 말고는 LGTM 입니다 ~

2023-09-22 21:50 UTC, 14KGun commented
https://github.com/sparcs-kaist/taxi-front/pull/665

@TaehyeonPark ....ㅋㅋㅋㅋ

2023-09-23 20:04 UTC, merged