#391 방 공유 퀘스트 완료 API 추가
sparcs-kaist/taxi-back pull request #392
Opened 2023-09-22 15:41 UTC by kmc7468

# Summary 

It closes #391
`/events/2023fall/quests` 라우터 아래에 있던 다양한 퀘스트 완료 요청 API를 `/events/2023fall/quests/complete/:questId` API로 통합하였습니다. 또, itemSchema에 instagramStoryStickerImageUrl 필드를 추가했습니다.

# Further Work 

- Nothing

2023-09-22 16:09 UTC, TaehyeonPark commented on src/lottery/services/items.js
> +      .find({}, "-isRandomItem -randomWeight")
개인적으로 어떤 필드들이 있는지 주석으로 적어주시면 좋을 듯 합니다!

2023-09-22 16:12 UTC, kmc7468 commented on src/lottery/modules/quests.js
> +    quest.isApiRequired = quest.isApiRequired || false;
오 좋네요! 이런 연산자가 JS에도 있는지 몰랐습니다. 바로 반영할게요!

2023-09-22 16:13 UTC, kmc7468 commented on src/lottery/modules/populates/transactions.js
> +    select: "-isRandomItem -randomWeight",
사실 isRandomItem과 randomWeight 외의 모든 값은 Frontend 쪽에 전달되어야 해서요! 이렇게 유지하는 것도 나쁘지 않을 것 같습니다.

2023-09-22 16:13 UTC, kmc7468 commented on src/lottery/services/items.js
> +      .find({}, "-isRandomItem -randomWeight")
위 리뷰의 코멘트와 같습니다. 말씀 감사합니다!

2023-09-22 16:16 UTC, TaehyeonPark approved these changes

2023-09-22 19:07 UTC, withSang commented on src/lottery/modules/populates/transactions.js
> +    select: "-isRandomItem -randomWeight",
새 필드가 추가되거나 기존 필드가 삭제될 때 @TaehyeonPark 님께서 말씀하신 방식이 더 오류가 발생할 가능성이 작아 안정적이기는 합니다 ㅎㅎ

2023-09-22 19:08 UTC, withSang commented on src/lottery/services/items.js
> +      .find({}, "-isRandomItem -randomWeight")
새 필드가 추가되거나 기존 필드가 삭제될 때 @TaehyeonPark 님께서 말씀하신 방식이 더 오류가 발생할 가능성이 작아 안정적이기는 합니다 ㅎㅎ

2023-09-22 19:17 UTC, withSang requested changes
API 호출이 필요한 quest 달성 조건들에서 코드 재사용성이 높아져 깔끔해진 것 같습니다!
몇 가지 작은 제안사항들을 남겨드립니다. 감사합니다!

2023-09-22 19:17 UTC, withSang commented on src/lottery/routes/docs/questsSchema.js
> +        type: "string",
questId로 받을 수 있는 값이 정해져 있기 때문에("roomSharing", "eventSharingOnInstagram", "purchaseSharingOnInstagram"), enum으로 검증이 가능합니다!
swagger enum 타입 사용법 문서: https://swagger.io/docs/specification/data-models/enums/

2023-09-22 19:17 UTC, withSang commented on src/lottery/services/quests.js
> +    if (!quest?.isApiRequired)
사용자가 `/events/2023fall/quests/complete/:questId` 엔드포인트에 잘못된 questId로 요청한 경우, quest의 값이 undefined가 되기 때문에 이 if문의 조건이 참이 될 것입니다.
지금 코드도 문제 없이 동작하지만, quest가 존재해야 하고, quest의 isApiRequired 값이 참이어야 함을 명시적으로 드러내기 위해 아래와 같이 조건을 더 명확히 명시할 수 있습니다!
```javascript
if (!quest || !quest?.isApiRequired)
```

2023-09-23 00:12 UTC, withSang approved these changes
이벤트 기간이 곧 시작되기도 하니만큼, 제가 조언드린 사항들은 머지 직전에 수정하셔도 문제 없다고 생각합니다!

2023-09-23 05:52 UTC, kmc7468 commented on src/lottery/services/quests.js
> +    if (!quest?.isApiRequired)
의도가 더 잘 보이는 것 같아 좋네요! 뒷부분 식을 `!quest.isApiRequired` 로 변경하여 반영하도록 하겠습니다!

2023-09-23 05:54 UTC, kmc7468 commented on src/lottery/modules/populates/transactions.js
> +    select: "-isRandomItem -randomWeight",
그러면 주석으로 다는 것보다는 기존 방식을 유지하는 편이 더 나을 것 같네요! 말씀 드린대로 isRandomItem과 randomWeight 외에는 프론트에 보여져야 할 정보라 생각해서 더 직관적인 방법으로 바꾼건데, 앞으로 필드가 더 추가될 수 있음을 고려하면 기존 방식이 더 좋은 면도 있는 것 같습니다.

2023-09-23 05:58 UTC, kmc7468 commented on src/lottery/routes/docs/questsSchema.js
> +        type: "string",
이런 것도 있었군요! 알려주셔서 감사합니다!

2023-09-23 06:02 UTC, 14KGun approved these changes
👍 수고하셨습니다 !

2023-09-23 06:03 UTC, merged