[WiP] TypeScript 지원
sparcs-kaist/taxi-back pull request #430
Opened 2023-11-07 11:36 UTC by withSang

# Summary 

It closes #159 
타입스크립트 지원을 추가합니다.

# Extra info 

To be confirmed

# Images or Screenshots 

To be confirmed

# Further Work 

- To be confirmed

2024-11-12 14:35 UTC, withSang commented on .eslintrc.cjs
> +              "Usage of relative parent imports is not allowed. Use path alias instead.",
:+1

2024-11-12 16:21 UTC, kmc7468 commented on .eslintrc.cjs
> +              "Usage of relative parent imports is not allowed. Use path alias instead.",
아.. lint 생각을 못하고 있었네요. CI에 lint도 같이 넣어버려야겠습니다!

2024-11-19 10:41 UTC, kmc7468 requested changes

2024-11-19 10:41 UTC, kmc7468 commented on src/modules/stores/aws.ts
> +  cb: (err: AWS.AWSError, data: AWS.S3.ListObjectsOutput) => void
data 타입이 상황마다 다 달라서 힘들 수도 있을 것 같아요 ㅠ

2024-11-19 10:41 UTC, kmc7468 commented on src/modules/stores/sessionStore.ts
> -const RedisStore = require("connect-redis")(expressSession);
음, `expressSession` 을 넘겨주는 부분이 TS로 옮겨진 코드에선 누락된 것 같은데요. redis와 연결했을 때 잘 작동되는지 테스트가 필요할 것 같습니다.

2024-11-19 10:41 UTC, kmc7468 commented on src/middlewares/authAdmin.ts
> +      ipWhitelist.map((x: any) => x.ip).indexOf(req.clientIP) < 0 // TODO: Remove any
여기 `any` 는 지울 수 있으면 지우는게 좋을 것 같네요

2024-11-19 10:41 UTC, kmc7468 commented on src/middlewares/information.ts
> +    req.connection.remoteAddress;
`req.connection` 이 deprecated 된 것 같은데 이번에 바꾸고 가도 좋을 것 같아요

2024-11-19 10:41 UTC, kmc7468 commented on src/middlewares/limitRate.ts
>  const limiter = rateLimit({
`index.ts`에서 사용된 이름과 통일성을 맞추기 위해 `limitRateMiddleware` 로 바꿔도 좋을 것 같아요.

2024-11-19 10:41 UTC, kmc7468 commented on src/middlewares/limitRate.ts
> -  },
이거는 왜 삭제된걸까요?!

2024-11-19 10:41 UTC, kmc7468 commented on src/views/loginReplacePage.ts
> +export default loginPage;
`loginReplacePage` 로 이름 맞추고 가면 좋을 것 같네요

2024-11-19 10:41 UTC, kmc7468 commented on src/views/loginReplacePage.ts
>      <head>
사소한 제안인데 들여쓰기 2칸으로 바꾸면 어떨까요 ㅋㅋㅋ

2024-11-19 10:41 UTC, kmc7468 commented on src/views/reportEmailPage.js
얘도 TS로 바꿔버리죠

2024-11-19 11:03 UTC, kmc7468 commented on src/index.ts
> +connectDatabase(mongoUrl);
코드 보다가 든 생각인데, DB랑 연결된 후에 아래에 있는 로직을 실행하도록 아예 바꾸면 어떨까요? `initializeFareDatabase` 같은 함수가 DB를 건드는 함수라서.. DB랑 연결된게 확인된 후 실행되는게 조금 더 적절할 것 같다는 생각이 들었어요. 아니면 해당 함수만 DB 연결된 후 실행되도록 바꾸는 것도 좋을 것 같습니다.

2024-11-19 11:05 UTC, kmc7468 commented on package.json
> +    "start": "npx tsc && tsc-alias && npx nodemon",
여긴 아마 `npx` 필요 없었던 걸로 기억합니다! 그리고 `nodemon.json` 파일과도 연관된건데, 매번 파일이 바뀔 때마다 컴파일을 다시 하는 방식은 좀 비효율적인 것 같아요. 증분 빌드를 활용하거나, 또는 `ts-node` 를 사용하는 것도 좋은 대안이 될 것 같습니다.

2024-11-19 11:15 UTC, kmc7468 commented on src/services/auth.js
> +const { user: userPattern } = require("@/modules/patterns").default;
메모: ESM에서 export default 한 것을 CJS에서 require를 통해 가져오려면 `.default` 가 있어야 오류가 안 뜹니다!

2024-11-19 11:18 UTC, kmc7468 commented on src/services/auth.js
> +const jwt = require("@/modules/auths/jwt").default;
이 친구는.. 확인이 필요할 듯

2024-11-19 12:32 UTC, kmc7468 commented on .eslintrc.cjs
> +              "Usage of relative parent imports is not allowed. Use path alias instead.",
추후 별도의 이슈/PR을 통해 작업하기로 결정하였습니다.

2024-11-19 12:33 UTC, cokia commented on src/middlewares/auth.ts
>      res.status(403).json({
이것도 컨벤션 이슈같은데, 저도 return 으로 처리하는게 직관적일 것 같다는 의견입니다

2024-11-19 12:38 UTC, kmc7468 commented on src/middlewares/auth.ts
> +import { type Request, type Response, type NextFunction } from "express";
컨벤션으로 결정되었습니다.

2024-11-19 12:40 UTC, kmc7468 commented on src/middlewares/auth.ts
> +const authMiddleware = (req: Request, res: Response, next: NextFunction) => {
컨벤션으로 결정되었습니다.

2024-11-19 12:57 UTC, kmc7468 commented on package.json
> +    "start": "npx tsc && tsc-alias && npx nodemon",
`ts-node` 쓰는걸로 결정했습니다.

2024-11-19 13:15 UTC, TaehyeonPark commented on src/middlewares/errorHandler.ts
> +import { type Request, type Response, type NextFunction } from "express";
-> import type { Request, Response, NextFunction } from "express";

2024-11-19 13:24 UTC, TaehyeonPark commented on src/middlewares/errorHandler.ts
> +  return res.status(500).send("internal server error");
if (res.headersSent) {
    next(err);
  } else {
    res.status(500).send("internal server error");
    return res.status(500).send("internal server error");
}

이런 컨벤션으로 가는 게 낫지 않을까요

2024-11-19 13:27 UTC, TaehyeonPark commented on src/middlewares/originValidator.ts
> +  return next();
next()에는 return 안붙이는 걸로

2024-11-19 14:02 UTC, kmc7468 commented on src/middlewares/information.ts
> +    req.connection.remoteAddress;
`req.ip` 라는 친구도 있네요.

2024-11-26 13:55 UTC, kmc7468 commented on src/middlewares/index.ts
> +export * from "./zod";
나중에 수정하면 좋을듯요~

2024-11-26 16:22 UTC, kmc7468 commented on src/modules/stores/sessionStore.ts
> +  session as sessionConfig,
다른 PR 열어서 진행하면 좋을 것 같습니다.

2024-11-26 16:23 UTC, kmc7468 commented on src/modules/stores/sessionStore.ts
> -const RedisStore = require("connect-redis")(expressSession);
버그 확인해서 수정했습니다~!

2024-11-26 18:11 UTC, kmc7468 commented on src/services/auth.js
> +const jwt = require("@/modules/auths/jwt").default;
실제로 잘못 사용한 부분이었어서 다른 곳도 확인하여 모두 수정 완료했습니다!

2024-11-26 18:22 UTC, kmc7468 commented on src/services/users.ts
> +    const newNickname = req.body.nickname; // TODO: Typing
차후 PR에서 Type 붙여야 합니다.

2024-11-26 18:39 UTC, TaehyeonPark commented on src/services/users.ts
> -const { userModel, banModel } = require("../modules/stores/mongo");
Convention 제안: @를 너무 막 쓰고 있는 듯 싶은데, @의 경우 .. 으로 상위 디렉토리(파일)를 참조하는 경우에는 @ 사용을 권장하고, 하위 디렉토리(파일) 및 현재 디렉토리(파일)를 참조할 경우 ./ 사용을 권장함.

2024-11-26 18:40 UTC, kmc7468 commented on src/services/users.ts
> -const { userModel, banModel } = require("../modules/stores/mongo");
좋은 생각인 것 같습니다! 다음주 마지막 회의에서 논의하고 결정해봐요

2024-11-26 18:50 UTC, TaehyeonPark approved these changes

2024-11-26 18:50 UTC, kmc7468 approved these changes
LGTM! 다들 정말 고생 많으셨습니다

2024-11-26 18:50 UTC, merged