#436 taxi-sample-generator 병합
sparcs-kaist/taxi-back pull request #437
Opened 2023-11-21 14:40 UTC by kmc7468

# Summary 

It closes #436
taxi-sample-generator를 taxi-back에 머지하였습니다.
기존 taxi-sample-generator 레포에 남겨진 커밋 로그도 taxi-back에 모두 합쳐졌습니다. (GitHub에선 안보이지만, git blame과 git log를 통해 확인할 수 있어요.)

# Further Work 

- Nothing

2023-11-21 15:06 UTC, kmc7468 commented
CI 쪽이 수정되었는데, 잘 수정했는지 확인해 주시면 감사할 것 같아요!
제가 CI 쪽은 잘 몰라서 ㅠㅠ 잘 했는지 모르겠네요.

2023-11-22 03:41 UTC, chlehdwon reviewed
큰 작업인데 수고가 많으십니다! 몇 부분은 기존 코드에 같이 병합해서 한 번에 관리하는 게 편해보이는데, 따로 관리하는 게 나을지는 한 번 논의해보면 좋을 것 같습니다 :)

2023-11-22 03:41 UTC, chlehdwon commented on src/sampleGenerator/.github/pull_request_template.md
> +- Do something...
taxi-back에 이미 있기 때문에 없어져도 괜찮을 것 같습니다

2023-11-22 03:41 UTC, chlehdwon commented on src/sampleGenerator/.github/workflows/push_image_ecr.yml
이 부분도 동일

2023-11-22 03:41 UTC, chlehdwon commented on src/sampleGenerator/Dockerfile
taxi-back의 Dockerfile과 같이 병합되어야 할 것 같은데 맞나요? @withSang @14KGun

2023-11-22 03:41 UTC, chlehdwon commented on src/sampleGenerator/.env.example
> +OCCURENCE_OF_ABORT=0.1
한 repo로 합치게 되는 거면 `.env`도 기존의 environment 파일과 같이 관리하도록 제안 드려봅니다.

2023-11-22 05:50 UTC, kmc7468 commented on src/sampleGenerator/Dockerfile
건님께서 Dockerfile은 유지되어야 한다고 말씀하셨습니다! 샘플 데이터 들어있는 DB만 띄울 수 있게 만들기 위함이라고 들었어요.

2023-11-22 06:06 UTC, chlehdwon commented on src/sampleGenerator/Dockerfile
@kmc7468 아아 맞네요😅 제가 헷갈렸습니다!!

2023-11-22 06:08 UTC, withSang reviewed
좋아 보입니다! 감사합니다 :)

2023-11-22 06:08 UTC, withSang commented on src/sampleGenerator/Dockerfile
현재 Docker는 배포할 때만 사용되고 있는데, 샘플 데이터를 만드는 과정까지 Docker화될 필요는 없어보여요! 저도 Dockerfile 없어도 된다고 생각해요 :)

2023-11-22 06:09 UTC, withSang commented on src/sampleGenerator/.env.example
> +OCCURENCE_OF_ABORT=0.1
제 생각도요!! 아래 환경변수들은 다 taxi-back의 optional env variable로 둘 수 있겠습니다.
```bash
#방과 각각의 방의 채팅 개수
NUM_OF_ROOMS=2
NUM_OF_CHATS=200
#채팅 간 최대 시간 간격(단위: 초, 소수도 가능)
MAXIMUM_INTERVAL_BETWEEN_CHATS=20
#새로운 채팅이 각각 입/퇴장 메시지일 확률(각각 10%)
OCCURENCE_OF_JOIN=0.1
OCCURENCE_OF_ABORT=0.1
```

2023-11-23 02:09 UTC, kmc7468 commented on .github/workflows/test_ci.yml
>              core.setFailed('Please update submodule to the latest version by using \"git submodule update --remote\"')
감사합니다! 반영되었어요.

2023-11-23 02:10 UTC, kmc7468 commented on src/sampleGenerator/Dockerfile
오늘(11/23) 회의에서 논의 후 결정해도 좋을 것 같습니다.

2023-11-23 02:10 UTC, kmc7468 commented on src/sampleGenerator/sampleData.json
> +    },
완료되었습니다!

2023-11-27 01:07 UTC, 14KGun commented on src/sampleGenerator/README.md
> +1. `pnpm run restoreDB`로 과거 DB를 덤프 파일로부터 복원할 수 있습니다.
index가 전부 1이네요??? ㅋㅋㅋ

그리고 
```
   \`\`\`
   #mongoDB 경로 (직접 입력해야 함 - 기본값은 mongodb://localhost:27017/local)
   DB_PATH=mongodb://localhost:27017/local
   #방과 각각의 방의 채팅 개수
   NUM_OF_ROOMS=2
   NUM_OF_CHATS=200
   #채팅 간 최대 시간 간격(단위: 초, 소수도 가능)
   MAXIMUM_INTERVAL_BETWEEN_CHATS=20
   #새로운 채팅이 각각 입/퇴장 메시지일 확률(각각 10%)
   OCCURENCE_OF_JOIN=0.1
   OCCURENCE_OF_ABORT=0.1
   \`\`\`
```
이 설명도 수정해주셔야 할 것 같네염 ㅎ

2023-11-27 01:07 UTC, 14KGun commented on src/sampleGenerator/security.js
> +});
```suggestion
const loadSampleData = async () => {
  const data = fs.readFileSync(sampleDataPath);
  return JSON.parse(data));
});
```

2023-11-27 01:45 UTC, withSang commented on src/sampleGenerator/README.md
> +1. `pnpm run restoreDB`로 과거 DB를 덤프 파일로부터 복원할 수 있습니다.
오 환경변수 수정 좋아요 ㅎㅎ
마크다운 문법 상 1. 로만 쓰는 것도 가능합니다. 중간중간에 새 항목이 추가될 때마다 새로 번호를 매겨야 하는 수고를 줄이기 위함이에요!
https://www.markdownguide.org/basic-syntax/#ordered-lists

2023-11-27 01:47 UTC, withSang commented on src/sampleGenerator/security.js
> +});
오 샘플 데이터 읽는 부분은 작성해주신 것처럼 비동기처리가 없어도 문제 없어보여요. 이렇게 되면 비동기 로직이 없어지니까 함수 선언에서 async를 빼야 합니다!

2023-11-27 06:29 UTC, 14KGun commented on src/sampleGenerator/README.md
> +1. `pnpm run restoreDB`로 과거 DB를 덤프 파일로부터 복원할 수 있습니다.
옹 새로운 사실.. 알았네염

2023-11-27 06:31 UTC, 14KGun commented on src/sampleGenerator/security.js
> +});
생각해보니깐 그럼 굳이 함수일 필요도 없는듯요?? ㅋㅋㅋ

```suggestion
const sampleData = JSON.parse(fs.readFileSync(sampleDataPath));
```

2023-11-27 06:34 UTC, withSang commented on src/sampleGenerator/security.js
> +});
오 그러네요!! 그리고 loadSampleData를 호출하는 코드도 고쳐야 해요

2024-01-06 12:10 UTC, kmc7468 commented on src/sampleGenerator/Dockerfile
11월 23일 회의에서 논의한대로 Docker 관련 파일을 모두 삭제했습니다.

2024-01-06 12:10 UTC, kmc7468 commented on src/sampleGenerator/.env.example
> +OCCURENCE_OF_ABORT=0.1
11월 23일 회의에서 논의한대로 .env.test 파일에 통합하였습니다.

2024-01-06 12:11 UTC, kmc7468 commented on src/sampleGenerator/README.md
> +1. `pnpm run restoreDB`로 과거 DB를 덤프 파일로부터 복원할 수 있습니다.
README 업데이트했습니다!

2024-01-06 12:11 UTC, kmc7468 commented on src/sampleGenerator/security.js
> +});
반영 완료했습니다! 좋은 의견 감사해요!

2024-01-06 12:14 UTC, kmc7468 commented
앗 tools 쪽 수정을 까먹고 안했네요! 금방 수정하겠읍니다 ㅜ

2024-01-06 12:29 UTC, kmc7468 commented
DB 덤프는 잘 되는 것 같은데, 복원이 잘 안되는 것 같습니다. 혹시 원인이 뭘까요? ㅠㅠ

오류가 뜨는 것도 아니고.. mongodb에 db도 생성되는데 collection들에 데이터가 안들어 있네요.

2024-01-06 12:36 UTC, kmc7468 commented
해결했습니다! dump 대신 dump/taxi를 인수로 넘겨주니 잘 작동합니다.

2024-01-10 09:26 UTC, 14KGun commented on .gitmodules
이 파일 지워도 될듯용

2024-01-10 09:26 UTC, 14KGun commented on sampleGenerator
🎉

2024-01-10 09:26 UTC, 14KGun commented on package.json
> +    "sample": "cd src/sampleGenerator && npm start && cd .."
이런식으로 `samplegenerator` 스크립트 실행시켜도 좋을 것 같네요

https://github.com/sparcs-kaist/taxi-front/blob/0a759afab95386cc5d9663a0e7cd77150f516ab0/package.json#L7

2024-01-11 10:47 UTC, chlehdwon requested changes
큰 작업 고생 많으셨습니다~!! 너무 잘하셨는데 소소하게 한 가지만 제안 드립니다!

2024-01-11 10:47 UTC, chlehdwon commented on src/sampleGenerator/src/testData.js
> +      kaist: new String(20230000 + num), // ^-^
젊어지는 택시 좋습니다 😁

2024-01-11 10:47 UTC, chlehdwon commented on src/sampleGenerator/.env.example
현재 구조에서 `.env.test`에 저 변수들을 정의해야 할텐데 현재 `.env.example`이 여기 위치한 게 어색한 것 같습니다!
(특히 처음 세팅하는 입장에서 안 헷갈리려면 저 example들도 `.env.example`과 같은 depth에 있으면 좋을 것 같아서요.)

기존 `.env.example`에 통합 시키는 것은 어떨까요? 어차피 개발 할 때  `DB_PATH`를 다르게 설정할 경우도 없을 거고, 저 밑에 변수들을 굳이 선언해서 변경할 경우가 많이 없을 것 같아서요. 차피 `loadenv.js`에서 default 값을 잘 설정해주었기 때문에 별도의 설정 변경 없이 자연스럽게 사용할 수 있을 것 같습니다!

2024-01-21 14:13 UTC, kmc7468 commented on .gitmodules
반영 완료했습니다!

2024-01-21 14:13 UTC, kmc7468 commented on src/sampleGenerator/.env.example
그렇네요! .env.example 파일도 통합해야 하는걸 놓쳤네요... 말씀해 주셔서 감사합니다! 반영 완료했어요.

2024-01-21 14:38 UTC, kmc7468 commented on package.json
> +    "sample": "cd src/sampleGenerator && npm start && cd .."
`pnpm -F taxisamplegenerator` 로 시도해 봤는데 안되네요! ㅜㅜ

2024-01-21 17:54 UTC, 14KGun approved these changes
👍

2024-01-23 02:21 UTC, chlehdwon approved these changes
LGTM!!! 고생많으셨습니다 :)

2024-01-23 13:32 UTC, merged