#450 택시비용 보여주기
sparcs-kaist/taxi-back pull request #451
Opened 2024-02-06 13:38 UTC by ybmin

# Summary 

It closes #450 

taxi-back 분들이 스타일이랑 코드 위치, 그리고 코드를 바꿔주시면 감사하겠습니다 😆
issue 페이지에 상세히 적어놓았습니다.

# Further Work 

- [ ] 작은 자원으로 진행할 수 있는 대안 db가 있다면, 해당 사항으로 넘어가야합니다.
- [ ] taxi-front에서 해당 정보를 보여주는 컴포넌트를 작성해야 합니다.

2024-03-09 12:10 UTC, ybmin commented
24h를 30분 단위로 분리 & 요일 정보도 하나로 관리, 0 ~ 6 (Sunday~Saturday) * 48 + 0 ~ 47 (0:00 ~ 23:30)

2024-03-12 12:32 UTC, kmc7468 commented on src/modules/stores/mongo.js
> +    start: { type: String, required: true }, // 출발지
ObjectId로 타입 변경 후 Location 참조하도록 수정해주시면 좋을 것 같습니다!

2024-03-12 12:32 UTC, kmc7468 commented on src/routes/fare.js
> +const { query } = require("express-validator");
express-validator 대신 ajv 쓰면 좋을 것 같아요!

2024-03-12 12:35 UTC, xMHW commented on src/services/fare.js
> +          `https://naveropenapi.apigw.ntruss.com/map-direction/v1/driving?start=${
외부 api 주소들은 Constant로 빼주셔도 좋을 것 같습니다.

2024-03-12 13:02 UTC, chlehdwon commented on src/services/fare.js
> +    console.log(err);
logger.info() 혹은 에러인 경우 logger.error()로 작성해주세요~!

2024-04-23 13:23 UTC, kmc7468 commented on src/modules/fare.js
> +      naverCloudApi["X-NCP-APIGW-API-KEY"] === null ||
이거 undefined일 수도 있을 것 같아서 그냥 !로 검사하면 어떨까요?

2024-04-23 13:54 UTC, chlehdwon requested changes
수고 많으셨습니다! 해당 리뷰 한 번 확인해주세요

2024-04-23 13:54 UTC, chlehdwon commented on src/services/fare.js
> +          function (err, docs) {
Taxi는 ES6 문법을 지향하기 때문에 화살표 방식으로 함수를 작성해주시면 좋습니다. 
```suggestion
          (err, docs) => {
```

관련 노션 문서 공유해드립니다.
https://www.notion.so/sparcs/ES6-3d8bbfc93f0c4630af19268ce5e8df77

2024-04-23 13:54 UTC, chlehdwon commented on src/modules/fare.js
> +      }, Promise.resolve());
`Promise.resolve()` 이 부분은 쓰신 이유가 따로 있으실까요? 
일반적인 async 함수 정의하는 것 같은데 생략해도 될 것 같습니다.

2024-04-23 13:54 UTC, chlehdwon commented on src/services/fare.js
> +  }, Promise.resolve());
위랑 같은 내용

2024-05-14 14:23 UTC, chlehdwon requested changes
네이버 지도 API ID/KEY 값은 공유되는 건가요? 공유되는 거면 slack에 올려주면 감사하겠습니다~!
문서화 부분은 제가 수정해서 commit 올려 놓을게요

2024-07-07 09:28 UTC, ybmin commented on src/modules/fare.js
> +};
아 너무 늦게 확인했네요 ㅠㅠ API 같은 경우는 아직 스팍스 계정으로 만들어 두지 않아서 아마 다음 회의 때 건의해보고 전달 드리겠습니다. 그리고 API KEY가 없을 때는 해당 에러 로그를 안 띄우도록 수정하겠습니다. 리뷰해 주셔서 감사합니당

2024-07-09 13:13 UTC, ybmin commented
[https://github.com/sparcs-kaist/taxi-back/pull/430 ](url) 가 머지된 후에 붙입니다.

2024-07-18 23:02 UTC, kmc7468 requested changes
자꾸 요청사항 드려서 죄송합니다...ㅠㅠ

2024-07-19 15:31 UTC, ybmin commented on src/modules/fare.js
> +        await new Promise((resolve) => setTimeout(resolve, 200));
비동기로 초기화 과정에서 240 번 정도 api를 날리는데 axios가 해당 요청을 못 버텨서 200ms걸어두고 진행 중입니다.
```suggestion
        await new Promise((resolve) => setTimeout(resolve, 200));
```

2024-07-19 15:40 UTC, ybmin commented on src/services/fare.js
> +      .clone();
그렇네용 여긴 필요하지 않은 것 같네요.

2024-07-19 16:35 UTC, ybmin commented on src/modules/fare.js
> +    location.map(async (from) => {
비동기 처리를 하는데 안 쓰다니 성능에 큰일 날뻔 했네요 ㅠㅠ 감사합니당

2024-07-20 01:32 UTC, kmc7468 approved these changes
LGTM! 저의 수많은 요청 사항 받아주시느라 고생 많으셨습니다~~ 

진짜 마지막 요청 사항만 반영 부탁드려요!! (제가 커밋 하나 해가지구 수정 전 git pull 필요합니다)

2024-07-20 01:32 UTC, kmc7468 commented on src/routes/fare.js
> +  validateQuery(fareZod.getTaxiFare),
이거 schema 쪽에서도 getTaxiFareHandler로 이름 바꿔주시면 좋을 것 같습니당

2024-07-20 01:32 UTC, kmc7468 commented on src/modules/fare.js
> +    .clone();
아직 clone을 쓰는 곳이 몇 군데 남아 있어요! 꼭 필요한게 아니라면 모두 lean으로 바꿔주시면 좋을 것 같네용~~

2024-07-24 13:51 UTC, merged