#471 introduce zod
sparcs-kaist/taxi-back pull request #484
Opened 2024-03-05 12:16 UTC by chlehdwon

# Summary 

It closes #471 

# Extra info 

# Images or Screenshots 

# Further Work

2024-03-14 05:39 UTC, kmc7468 requested changes
수고하셨습니다~~ zod가 확실히 깔끔하고 좋네요. 코멘트 확인 부탁드립니당

2024-03-14 05:39 UTC, kmc7468 commented on src/lottery/routes/items.js
> -const { validateParams } = require("../../middlewares/ajv");
여기도 주석 남겨두면 좋겠네요!

2024-03-14 05:39 UTC, kmc7468 commented on src/modules/patterns.js
> +  objectId: RegExp("^[a-fA-F\\d]{24}$"),
👍

2024-03-14 05:39 UTC, kmc7468 commented on src/routes/docs/utils.js
>  const objectIdPattern = `^[a-fA-F\\d]{24}$`;
patterns.js에 있는 objectId를 가져다 쓰면 어떨까요?

2024-03-14 05:39 UTC, kmc7468 commented on src/routes/docs/schemas/roomsSchema.js
> +    name: z.string().regex(room.name),
기존에는 Object Id로 되어있었는데, 기존 버전이 잘못됐었던거겠죠??

2024-03-14 05:39 UTC, kmc7468 commented on src/routes/docs/utils.js
>    rooms: {
여기도 옮길 수 있는 것들은 patterns.js로 옮겨도 좋을 것 같습니다.

2024-03-14 05:39 UTC, kmc7468 commented on src/routes/docs/utils.js
> +    return {};
오류 발생했다고 로깅하면 어떨까요?

2024-03-14 05:39 UTC, kmc7468 commented on src/middlewares/zod.js
> +    const result = schema.safeParse(req);
zod를 쓰니 ajv 쓸 때보다 코드가 훨씬 간결해졌네요..!

2024-03-14 05:49 UTC, chlehdwon commented on src/lottery/routes/docs/schemas/globalStateSchema.js
> +      inviter: z.string().regex(objectId),
https://zod.dev/?id=optional
https://zod.dev/?id=partial
공식 문서를 읽어보니 둘의 역할이 비슷한 것 같습니다.

partial을 사용한 이유는
1. 기존 swagger 문서와 유사하게 optional한 attribute를 일괄적으로 정의하는 스타일이고
2. 만약 attribute 구성은 같지만 optional한 attribute가 다를 경우 (저희 room object가 좋은 예시가 되겠네요) 저 뒤에만 바꿔주는 방식으로 코드가 재사용 가능하다는 점이 있습니다.

2024-03-14 05:50 UTC, chlehdwon commented on src/lottery/routes/docs/schemas/itemsSchema.js
좋은 생각입니다! 추후에 추가 해놓겠습니다

2024-03-14 05:51 UTC, chlehdwon commented on src/routes/docs/schemas/roomsSchema.js
> +    name: z.string().regex(room.name),
넵!! 저건 제가 처음에 잘못 쓴 것 같아서 수정한 상태입니다.

2024-03-14 05:54 UTC, chlehdwon commented on src/routes/docs/utils.js
>    rooms: {
아 저 부분이 코드 재사용을 못하는 이유는 swagger는 정규표현식을 string 형태로 넣어주었고, zod는 정규표현식을 RegExp 형태로 받기 때문입니다. 조만간 json 형태의 swagger도 zod를 활용하는 방향으로 이전하는게 깔끔하지 않을까 싶습니다...

2024-03-14 05:56 UTC, chlehdwon commented on src/routes/docs/utils.js
> +    return {};
넵넵 좋습니다!!

2024-03-14 05:56 UTC, chlehdwon commented on src/routes/docs/utils.js
>  const objectIdPattern = `^[a-fA-F\\d]{24}$`;
아 저 부분이 코드 재사용을 못하는 이유는 swagger는 정규표현식을 string 형태로 넣어주었고, zod는 정규표현식을 RegExp 형태로 받기 때문입니다. 조만간 json 형태의 swagger도 zod를 활용하는 방향으로 이전하는게 깔끔하지 않을까 싶습니다...

2024-03-14 05:57 UTC, kmc7468 commented on src/lottery/routes/docs/schemas/globalStateSchema.js
> +      inviter: z.string().regex(objectId),
오오 그렇군요! 답변 감사합니다

2024-03-14 05:58 UTC, kmc7468 commented on src/routes/docs/utils.js
>  const objectIdPattern = `^[a-fA-F\\d]{24}$`;
아하..

2024-03-14 05:58 UTC, chlehdwon commented on src/middlewares/zod.js
> +    const result = schema.safeParse(req);
저도 쓰면서 아주 편하고 좋더라고요 :)

2024-03-16 06:27 UTC, chlehdwon commented on src/routes/docs/utils.js
>  const objectIdPattern = `^[a-fA-F\\d]{24}$`;
아 근데 swagger도 RegExp 형태로 넣어줘도 잘 받아서 pattern.js와 완벽 연동 가능할 것 같아요!

2024-03-16 07:01 UTC, chlehdwon commented on src/routes/docs/utils.js
>  const objectIdPattern = `^[a-fA-F\\d]{24}$`;
이 부분을 재사용해서 관리하는게 깔끔한 것 같아서 RegExp를 string으로 변환해서 사용하도록 일단 변경해놓았습니다~!
RegExp 객체에 source attribute를 사용하면 된다고 하네요.
https://stackoverflow.com/questions/39154255/converting-regexp-to-string-then-back-to-regexp

2024-03-16 11:20 UTC, kmc7468 approved these changes
LGTM! 수고하셨습니다..!

2024-03-16 11:21 UTC, kmc7468 commented on src/routes/docs/utils.js
>  const objectIdPattern = `^[a-fA-F\\d]{24}$`;
오 이런 속성이 있었군요. 확인 감사합니다!

2024-03-19 11:31 UTC, merged