#516 blockedlist
sparcs-kaist/taxi-back pull request #519
Opened 2024-05-20 17:39 UTC by TaehyeonPark

# Summary 

It closes #516 

`ban` 관련 모든 api는 `/users` router의 하위 api로 동작합니다.
- `/users/isBanned`
- `/users/getBanRecord`

2024-05-21 14:12 UTC, kmc7468 commented on src/modules/stores/mongo.js
> +    default: null,
`required: true` 가 되면 더 좋을 것 같습니다

2024-05-21 14:50 UTC, chlehdwon requested changes

2024-05-21 14:50 UTC, chlehdwon commented on src/services/users.js
> +const isBanned = async (req, res) => {
통일성을 위해 `isBannedHandler`와 같이 ~~Handler로 끝나도록 함수명 작성해주세요~!

2024-05-21 14:50 UTC, chlehdwon commented on src/services/users.js
> +const getBanRecord = async (req, res) => {
위와 동일

2024-05-21 14:50 UTC, chlehdwon commented on src/routes/docs/users.js
> +                    example: "664b5c1bfd906295bc0639a9",
objectId의 경우 해당 라인 추가하고 pattern을 통해 문서화를 진행하면 자동으로 example이 생성됩니다! 실제 objectId를 사용하는 것보다 해당 방법을 사용하는걸 권유드립니다.
`const { objectId } = require("../../modules/patterns"); `
```suggestion
                    pattern: objectId.source,
```

2024-05-21 14:50 UTC, chlehdwon commented on src/services/users.js
> +    const now = Date.now();
생각해보니 req.timestamp에도 시간정보가 담겨 있어서 이거 사용해도 될 것 같네요~!

2024-05-21 14:50 UTC, chlehdwon commented on src/services/users.js
> +    console.log(result);
console.log 제거해주세요~!

2024-05-27 15:22 UTC, TaehyeonPark commented on src/routes/docs/users.js
> +                    example: "664b5c1bfd906295bc0639a9",
오! 그런 방법이 있었군요! 알려주셔서 감사합니다!

2024-05-27 15:29 UTC, TaehyeonPark commented on src/services/users.js
> +    console.log(result);
앗! 깜빡했네요! 제가 미처 확인 못한 부분 짚어주셔서 감사합니다!

2024-05-27 16:19 UTC, chlehdwon approved these changes
LGTM!! 수고많으셨습니다 :)

2024-05-27 18:00 UTC, kmc7468 requested changes
Blocked List 자체는 구현이 잘 된 것 같습니다! 다만 실제 서비스 정지로 이어지는 코드도 필요할 것 같아요. 별도 PR로 분리해서 진행해도 될 것 같긴 합니다.

2024-05-27 18:08 UTC, kmc7468 commented on src/routes/docs/users.js
> +                    description: "사용자의 UUID",
UUID 보다는 단순히 Object ID라고 하는 것이 더 적절한 표현일 것 같아요!

2024-05-27 18:09 UTC, kmc7468 commented on src/services/users.js
> +      return res.status(400).json("Users/isBanned : there is no ban record");
빈 Array는 true로 평가되기 때문에, 이 부분은 사실 500 Internal Server Error로 생각하는게 더 좋을 것 같습니다.

2024-05-27 18:54 UTC, kmc7468 approved these changes
LGTM! 빠른 수정사항 반영 감사드립니다. 수고하셨습니다!

2024-05-27 18:54 UTC, merged