#527 회원 탈퇴 구현
sparcs-kaist/taxi-back pull request #528
Opened 2024-07-30 02:35 UTC by kmc7468

# Summary 

It closes #527 
회원 탈퇴를 구현합니다. 기존 User Schema에 존재하던 withdraw 필드를 활용해 Soft Delete 기반의 회원 탈퇴를 구현하였습니다. 추가로, 기존에 사용하던 userId는 SPARCS SSO에서 넘어오는 고유한 ID이기 때문에, 회원 탈퇴 후 재가입하는 경우를 적절히 처리하기 위해 불가피한 경우를 제외하면 userOid를 사용하도록 변경했습니다. 

# Further Work 

- Frontend 작업 필요

2024-10-08 14:07 UTC, kmc7468 commented on src/modules/socket.js
> +      authorProfileUrl: chat.authorId?.profileImageUrl ?? null,
탈퇴한 계정의 경우에는 null을 넣어서 드리고 프론트엔드에서 별도로 처리하는 식으로 구현하려고 했는데, 더 좋은 방법이 있을까요?

2024-10-08 14:09 UTC, kmc7468 commented on src/modules/socket.js
> +          return user?.nickname;
원래 구현이 이렇게 되어 있더라구요..! 개인적인 뇌피셜로는 한 번에 여러 명이 입장할 수도 있어서 이렇게 만들어 두신게 아닌가 싶습니다.

2024-10-08 14:09 UTC, kmc7468 commented on src/modules/socket.js
> +          return user?.nickname;
이번 기회에 함께 수정해 버릴까요?

2024-12-03 13:08 UTC, TaehyeonPark commented on src/lottery/services/publicNotice.js
> +          .findOne({ _id: user.userId, withdraw: false })
혹시 나중에 코드볼때 헷갈릴 것 같아서
`// user.userId는 userOid입니다.`
이런 주석 하나만 달아주시면 좋을듯 합니다

2024-12-03 13:15 UTC, TaehyeonPark approved these changes
LGTV~

2025-01-14 09:53 UTC, kmc7468 commented
자주 헷갈려서 남기는 메모
- `User` Document에 있는 `id` -> SPARCS SSO의 UID
- `User` Document에 있는 `_id` -> MongoDB의 Object ID

SID는 세션 스토어에만 저장됨

2025-01-14 12:30 UTC, kmc7468 commented
![image](https://github.com/user-attachments/assets/f96b2b74-4290-436c-a490-a11942769eaa)

탈퇴 후 새로운 계정으로 같은 방에 재입장했을 때, 입장/퇴장 안내 메세지가 새 계정의 닉네임으로 표시되는 문제가 있어요.

2025-01-14 12:48 UTC, kmc7468 commented
비슷한 이유로 입장 후 탈퇴하면 닉네임이 안뜨는 문제도 있습니다. 이 문제는 프론트랑 같이 해결이 필요할듯 @jinhyeonkwon 

![image](https://github.com/user-attachments/assets/65ebf3e1-100e-40fa-9e33-26e579fdf602)

2025-01-14 12:55 UTC, kmc7468 commented on src/services/notifications.js
> +    );
oid만 필요한데도 탈퇴 여부를 확인하기 위해 userModel에 쿼리하는 코드가 생각보다 많이 있네요.. 어떻게 하는게 좋을지 고민이 필요할 것 같습니다

2025-01-21 11:09 UTC, kmc7468 commented on src/services/reports.js
> +    const user = await userModel.findOne({ _id: req.userOid, withdraw: false });
메모: 탈퇴한 유저에 대한 신고는 채널톡을 통해 문의하는 것으로 정책을 결정했습니다.

2025-01-21 11:10 UTC, kmc7468 commented
최근 두 코멘트를 통해 언급한 버그는 Chat Document에서 content에 userId가 저장되어서 발생한 문제였습니다. DB 마이그레이션 및 content에 userOid를 저장하도록 변경하는 것을 통해 해결하고자 합니다.

2025-02-04 16:47 UTC, TaehyeonPark commented on src/modules/socket.js
>          inOutUserIds.map(async (userId) => {
이거 userOid로 바꿔주시면 좋을 것 같아요

2025-02-04 16:48 UTC, TaehyeonPark commented on src/modules/socket.js
> +          const user = await userModel.findById(userId, "nickname");
여기도 동일하게

2025-02-04 16:48 UTC, TaehyeonPark commented on src/modules/socket.js
> +          return user?.nickname;
여기도 동일하게

2025-02-04 18:11 UTC, TaehyeonPark commented on src/modules/stores/mongo.ts
참고로 const banSchema에서   userSid: { type: String, required: true }의 userSid를 id로 바꿔야합니다

2025-02-04 18:27 UTC, TaehyeonPark requested changes
LGTM~!

2025-02-04 18:37 UTC, TaehyeonPark approved these changes
Good!
수고하셨습니다~

2025-02-05 01:34 UTC, cokia approved these changes

2025-02-05 18:38 UTC, merged