#520 ban 여부에 따른 서비스 이용 제한
sparcs-kaist/taxi-back pull request #530
Opened 2024-08-12 13:09 UTC by TaehyeonPark

# Summary 

It closes #520 

- 방 생성/참여 기능에 대하여 이용 정지 상태인 경우 생성/참여를 제재합니다.

2024-09-02 08:18 UTC, kmc7468 requested changes
banRecord 확인과 관련하여 중복되는 코드가 많은데, 미들웨어로 분리하면 어떨까요?

2024-09-02 15:05 UTC, kmc7468 requested changes

2024-09-02 15:05 UTC, kmc7468 commented on src/modules/ban.js
> +        var banErrorMessage = `Rooms/create : user ${req.userId} (${req.session.loginInfo.sid}) is temporarily restricted from creating rooms until ${formattedExpireAt}.`;
나중에 case가 너무 많아질 것 같아서 염려가 됩니다. Endpoint 이름은 `service` 변수에 담겨있으니 그것을 사용하면 될 것 같고, 에러 메세지의 경우에는 언제까지 차단됐다는 메세지만 포함해도 괜찮을 것 같습니다. (그리고 제가 알기론 req.userId랑 req.session.loginInfo.sid가 같은 값으로 알고 있어요!)

2024-09-02 15:05 UTC, kmc7468 commented on src/modules/ban.js
> +        $gte: req.timestamp,
큰 차이는 없을 것 같은데 저는 이럴 때 gte보다는 gt를 사용하는걸 선호하긴 합니다! (expireAt이 이때부터 차단 해제된다는 의미니까요) 이건 그냥 optional로 원하시면 수정해주셔도 될 것 같습니다.

2024-09-02 15:05 UTC, kmc7468 commented on src/modules/ban.js
> +  if (banRecord != undefined) {
`!==` 사용해 주세요!

2024-09-03 13:11 UTC, cokia approved these changes
LGTM! 고생하셨습니다~!

2024-09-03 13:11 UTC, cokia commented on src/modules/ban.js
> +        bans[0]
디비에서 가져올때 expireAt 순서로 소팅해서 가져오면 불필요한 .reduce()를 줄일 수 있을 것 같아요..!

2024-09-03 13:37 UTC, kmc7468 requested changes

2024-09-03 13:37 UTC, kmc7468 commented on src/services/rooms.js
> +    if (banErrorMessage != undefined) {
여기도 `!==` 로 부탁드려요!

2024-09-03 13:37 UTC, kmc7468 commented on src/services/rooms.js
> +    if (banErrorMessage != undefined) {
여기도 `!==` 로 부탁드려요!

2024-09-04 03:58 UTC, kmc7468 requested changes

2024-09-04 03:58 UTC, kmc7468 commented on src/middlewares/ban.js
> +  console.log(`req.originalUrl: ${req.originalUrl}`);
저희 로그 남길 땐 `logger` 사용해야 합니다. 그리고 특이사항이 있는게 아니라면 이 내용은 로깅 안하는게 더 좋을 것 같아요!

2024-09-04 03:58 UTC, kmc7468 commented on src/middlewares/ban.js
> +    "/rooms/create": "service",
이런 상황에는 Object 대신 Map을 쓰는게 좋아요!

2024-09-04 03:58 UTC, kmc7468 commented on src/routes/rooms.js
> +router.use(require("../middlewares/ban"));
`router.use` 보다는 각 Endpoint마다 미들웨어를 달아주는게 좋을 것 같아용

2024-09-04 05:43 UTC, TaehyeonPark commented on src/routes/rooms.js
> +router.use(require("../middlewares/ban"));
auth middleware 바로 아래로 올리는 것으로 논의 완료

2024-09-04 06:58 UTC, kmc7468 approved these changes
LGTM..! 많은 요청사항 들어주셔서 감사합니다

2024-09-04 06:59 UTC, merged