Add: add ban features into event code
sparcs-kaist/taxi-back pull request #544
Opened 2024-09-06 15:44 UTC by TaehyeonPark

# Summary 

It closes #541

2024-09-07 06:52 UTC, kmc7468 requested changes
수고하셨습니다! 코멘트 확인 부탁드려요

2024-09-07 06:52 UTC, kmc7468 commented on src/lottery/middlewares/eventValidator.js
> +  next();
에러 발생했을 땐 next를 호출하면 안됩니다!

2024-09-07 06:52 UTC, kmc7468 commented on src/lottery/modules/contracts.js
> +const completeFirstLoginQuest = async (req, userId, timestamp) => {
req에 이미 userOid가 포함되어 있어서, req를 받을거라면 `userId` 매개변수는 필요하지 않을 것 같습니다. (주석도 업데이트 부탁드려요)

2024-09-07 06:52 UTC, kmc7468 commented on src/lottery/middlewares/eventValidator.js
> +    const eventStatus = await eventStatusModel
개인적으로는 이렇게 eventStatus를 가져오는 미들웨어보다는 필요한 services에서만 가져다 쓰는게 좋을 것 같다고 생각해요. 기존 코드에 user를 가져오는 미들웨어가 없고 필요한 services에서 직접 조회해서 쓰는 것처럼요. 물론 성능 차이는 거의 없겠지만, service에 따라 eventStatus를 단순히 조회만 하는 경우가 있고, 수정해야 하는 경우도 있는데 후자의 경우에는 (미들웨어가 있으면) query가 2번 발생하게 됩니다.

2024-09-07 06:52 UTC, kmc7468 commented on src/lottery/middlewares/eventValidator.js
> +    const eventStatus = await eventStatusModel
다른 백엔드 분들은 어케 생각하시는지도 궁금하네요!

2024-09-10 12:39 UTC, TaehyeonPark commented on src/lottery/modules/contracts.js
> +const completeFirstLoginQuest = async (req, userId, timestamp) => {
저희 quest 중에서 invitor의 userOid를 받아서 처리해야하는 부분이 있는데, req에는 아마 client의 userOid 값만 있어서 구분을 위해서는 userId parameter가 필요해보여요!

2024-09-24 14:52 UTC, TaehyeonPark commented on src/lottery/middlewares/eventValidator.js
> +    const eventStatus = await eventStatusModel
계속 사용하는 것으로 결정

2024-09-24 14:53 UTC, TaehyeonPark commented
> 수고하셨습니다! 코멘트 확인 부탁드려요

2025-04-23 00:28 UTC, kmc7468 requested changes
작업 고생하셨습니다! 코멘트 확인 부탁드려요..!

2025-04-23 00:28 UTC, kmc7468 commented on src/index.ts
> +  banMiddleware,
import를 지금 알파벳 순서로 맞춰놨는데, 요거에 맞춰주시면 좋을 것 같아요! (prettier에 import 자동 정렬을 넣으면 좋겠군요)

2025-04-23 00:28 UTC, kmc7468 commented on src/index.ts
> +// [Middleware] 모든 API 요청에 대하여 origin 검증
주석도 같이 업데이트 해주실 수 있나요?

2025-04-23 00:28 UTC, kmc7468 commented on src/lottery/middlewares/eventValidator.js
TS로 마이그레이션 완료되었으니 이 JS 파일은 삭제하면 될 것 같습니다.

2025-04-23 00:28 UTC, kmc7468 commented on src/lottery/middlewares/eventValidator.ts
> +import logger from "../../modules/logger";
이런 경우에는 `@/modules/logger` 로 간단하게 import할 수 있어요!

2025-04-23 00:28 UTC, kmc7468 commented on src/lottery/middlewares/eventValidator.ts
> + * @param req  eventStatus가 성공적일 경우 req.eventStatus = eventStatus로 들어갑니다.
사소한건데.. 여기 공백이 2개 있습니다 ㅋㅋㅋㅋㅋ ㅠ

2025-04-23 00:28 UTC, kmc7468 commented on src/lottery/middlewares/eventValidator.ts
> +const eventValidator: RequestHandler = async ( req, res, next ) => {
prettier 적용 안된 것 같은데 확인해 주실 수 있나요?

2025-04-23 00:28 UTC, kmc7468 commented on src/lottery/middlewares/eventValidator.ts
> +export default eventValidator;
`src/middlewares` 파일에 있는 미들웨어들을 보시면, `authMiddleware` 와 같이 Middleware로 이름을 끝내는게 컨벤션입니다! 맞춰서 이름 수정해 주실 수 있나용?

2025-04-23 00:28 UTC, kmc7468 commented on src/lottery/modules/contracts.js
> + * @param {string} sid - user의 sid입니다.
엇 주석 업데이트가 안된걸까요? sid라는 파라미터는 없는 것 같아서요!

2025-04-23 00:28 UTC, kmc7468 commented on src/lottery/modules/quests.js
> +const completeQuest = async (timestamp, userId, quest) => {
헉 이거 파라미터 순서가 왜 바뀐걸까요? 바꾸신 이유가 있다면 주석에서도 같이 순서 변경 부탁드려요!

2025-04-23 00:28 UTC, kmc7468 commented on src/lottery/modules/quests.js
> +    if (!eventStatus) return null; //
!

2025-04-23 00:28 UTC, kmc7468 commented on src/lottery/routes/invites.js
> +router.use(require("../../middlewares/ban").default);
저희 ban 미들웨어가 index.ts 파일에 달려있어서, 이런 곳에선 use 안해주셔도 됩니다!

2025-04-23 00:28 UTC, kmc7468 commented on src/lottery/services/invites.js
> +      // !!banErrorMessage ||
!

2025-04-23 00:28 UTC, kmc7468 commented on test/services/rooms.js
> +      },
이제 sid가 필요 없을 것 같은데, 이 부분은 삭제해도 될 것 같아요.

2025-04-23 00:28 UTC, kmc7468 commented on src/middlewares/ban.ts
> +  ["/rooms/create", "service"], // checked
checked의 의미는 뭔가요?

2025-05-20 12:51 UTC, kmc7468 requested changes
고생하셨습니다! 요청 사항 확인 부탁드려요~~

2025-05-20 12:51 UTC, kmc7468 commented on src/index.ts
> +// [Middleware] Event 관련 API 요청에 대하여 Ban 여부 검증
이벤트 뿐만이 아니라 서비스 전체에도 제한을 걸 수 있어서, 이 부분 반영해서 주석 수정되면 좋을 것 같습니다!

2025-05-20 12:51 UTC, kmc7468 commented on src/lottery/middlewares/eventValidator.ts
> +    res.status(500).json({
저희 res를 써서 응답을 전송할 때는 반드시 return을 붙이기로 컨벤션이 정해져 있습니다!

2025-05-20 12:51 UTC, kmc7468 commented on src/lottery/modules/quests.js
> +    if (!eventStatus) return null;
ban middleware를 거치지 않고 completeQuest 함수가 호출되지 않는 경우도 있어서, 이런 경우도 적절한 핸들링이 필요할 것 같습니다! (예: contracts 모듈의 completeNicknameChangingQuest 함수를 호출하는 경우 등)

2025-05-20 12:51 UTC, kmc7468 commented on src/lottery/services/globalState.js
> -        inviterStatus.isBanned ||
여기도 벤 체크가 필요할 것 같습니다.

2025-05-20 12:51 UTC, kmc7468 commented on src/middlewares/ban.ts
> +  console.log(req.originalUrl);
로깅이 꼭 필요하다면 `logger` 객체를 사용해 주시고, 테스트 목적으로 사용하신거라면 삭제 부탁드립니당

2025-05-20 12:51 UTC, kmc7468 commented on src/middlewares/ban.ts
> +        console.log(`Banned at ${req.originalUrl}`);
여기도..!

2025-05-20 12:51 UTC, kmc7468 commented on src/middlewares/ban.ts
> +  serviceMapper.forEach(async (value, key, map) => {
로직을 2단계로 쪼개면 좋을 것 같습니다. 1. serviceMapper에서 매칭된 prefix를 찾는 로직과 2. Response를 전송하는 로직으로 쪼개면 더 직관적일 것 같아요.

2025-05-20 12:51 UTC, kmc7468 commented on src/modules/ban.ts
> +    console.log(`ban.ts/bans: ${bans}`);
여기 로그도 필요 없으시면 지워주세용

2025-09-30 12:15 UTC, kmc7468 commented on src/middlewares/auth.ts
> +  req.userId = id;
이름을 `userUid` 라고 하면 어떨까요? 예전에 `userId` 였던 시절에 objectid인지 sso에서 넘어오는 uid인지 항상 헷갈렸어가지구 명확하게 이름을 지어주면 더 좋을 것 같아요.

2025-09-30 12:16 UTC, kmc7468 commented on src/middlewares/ban.ts
> +  { url: "/events/2025spring/quests", value: "2025-spring-event" },
가을 이벤트에 맞춰서 수정하면 좋을 것 같습니다!

2025-09-30 12:17 UTC, kmc7468 commented on src/modules/stores/mongo.ts
> +  userId: { type: String, required: true },
여기서도 `userUid` 로 해주면 더 명확하고 좋을 것 같습니다!

2025-09-30 12:17 UTC, kmc7468 commented on src/modules/stores/mongo.ts
> +      "2024-fall-event"
첫 적용이 이번 가을 이벤트가 될 것 같은데, `"2025-fall-event"` 만 넣어둬도 좋을 것 같습니다!

2025-09-30 12:19 UTC, kmc7468 commented on src/index.ts
> +app.use(originValidatorMiddleware);
originValidatorMiddleware가 지금 2개 있는데, 혹시 이 위치에서 필요한 이유가 있을까요??

2025-09-30 12:19 UTC, kmc7468 commented on src/lottery/middlewares/eventValidator.ts
> +const eventBanMiddleware: RequestHandler = async (req, res, next) => {
함수 이름을 파일 이름에 맞춰서 `eventValidator` 가 되면 좋을 것 같아요!

2025-09-30 12:20 UTC, kmc7468 commented on test/services/rooms.ts
> +      },
이거는 이제 필요 없을 것 같아요!

2025-09-30 12:20 UTC, kmc7468 commented on test/services/rooms.ts
> +      userOid: testUser2._id,
userOid가 2번 들어가 있어요! 아마 하나는 `userUid` 로 바꿔주셔야 할 것 같네요

2025-09-30 12:29 UTC, thxx132 commented on src/types/index.d.ts
> +      userId?: string;
이것도 userUid로 바뀌어야 할 것 같습니다

2025-10-28 12:22 UTC, kmc7468 requested changes
이번이 진짜 제가 남기는 마지막 리뷰입니다... ㅠㅠ

2025-10-28 12:22 UTC, kmc7468 commented on src/lottery/index.js
> -lotteryRouter.use(require("../middlewares/originValidator").default);
엇 이 친구는 있어야 할 것 같기도.. 지우신 이유가 있나요?

2025-10-28 12:22 UTC, kmc7468 commented on src/services/users.ts
> +        userId: req.userUid,
mongo.ts 파일을 보니 필드 이름이 userUid로 되어 있습니다..! 여기도 맞춰줘야 할 것 같네용

2025-10-28 12:22 UTC, kmc7468 commented on src/middlewares/ban.ts
> +  value: string;
이거 value를 string 타입으로 두기보다는.. 몽고DB 스키마 파일에서 자동 추론된 타입에서 뽑아서 쓰는게 더 type-safe하고 좋을 것 같습니다!

2025-10-28 12:22 UTC, kmc7468 commented on src/middlewares/ban.ts
> +      return res.status(400).json({
400보다는 403이 더 적절한 코드일 것 같습니다

2025-10-30 04:23 UTC, thxx132 commented on src/lottery/services/invites.js
> +    if (!inviterStatus || !inviterStatus.isInviteUrlEnabled)
inviterStatus.isBanned는 왜 사라졌나요?

2025-10-30 04:24 UTC, thxx132 commented on src/lottery/services/invites.js
> +    if (!inviterStatus || !inviterStatus.isInviteUrlEnabled)
라우터에서 검증하기 때문에 사라졌다면 주석 2번도 같이 없애주시면 좋을 것 같아요!

2025-10-30 04:26 UTC, thxx132 commented on src/modules/ban.ts
> +        userId: userId.id,
여기도 userUid로 바꿔야할 것 같습니다!

2025-10-30 04:39 UTC, thxx132 commented
아직 반영 안된 예전 코멘트들도 있는 것 같은데, 그런 것들 반영해주시고, 완료되었다면 각각 resolve해주시면 좋을 것 같아요

2025-11-04 11:26 UTC, Halo-sparcs commented on src/lottery/index.js
> -lotteryRouter.use(require("../middlewares/originValidator").default);
originValidator가 다른 event api보다 먼저 적용되는 것 같아서 아예 lotteryRouter를 originValidatorMiddleware 아래에 둘 생각으로 지웠습니다. 다음 commit의 src/index.ts에서 lotteryRouter의 위치를 조정할 예정입니다.

2025-11-11 13:35 UTC, kmc7468 approved these changes
LGTM! 고생하셨습니다
드디어 저희 숙원 사업이 하나 완료됐네요

2025-11-12 16:32 UTC, thxx132 approved these changes

2025-11-17 15:11 UTC, merged