#554 송금 독측 메일 관련 기능
sparcs-kaist/taxi-back pull request #555
Opened 2024-10-29 12:52 UTC by MinjaeKimmm

# Summary 

It closes #554 

# Extra info 

# Images or Screenshots 

# Further Work 

- Do something...

2025-07-22 15:10 UTC, kmc7468 requested changes
고생하셨습니다! 컨벤션 관련해서 몇 가지 코멘트 남겨드렸는데 확인 부탁드립니다~~

2025-07-22 15:10 UTC, kmc7468 commented on src/routes/emails.ts
> +router.get("/open-tracking", emailHandler);
zod 붙여주세요!

2025-07-22 15:10 UTC, kmc7468 commented on src/modules/stores/mongo.ts
> +});
타입 정의가 필요할 것 같습니다

2025-07-22 15:10 UTC, kmc7468 commented on src/modules/email.ts
>   * @return {Promise<boolean>} 이메일 전송에 성공하면 true를, 실패하면 false를 반환합니다.
JSDoc에서 타입 관련된 정보만 지워주실 수 있나요? 어짜피 함수에 다 나와있어서 JSDoc에 불필요하게 타입 정보를 명시할 필요가 없을 것 같습니다!

2025-07-22 15:10 UTC, kmc7468 commented on src/index.ts
> +  emailRouter,
아마 이거 정렬이 알파벳 순으로 되어 있을거라 맞춰 주실 수 있나요?

2025-07-22 15:10 UTC, kmc7468 commented on src/services/email.ts
> +      Buffer.from("R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==", "base64")
이건 혹시 어떤 이미지..인걸까요 ㅋㅋㅋ

2025-07-29 07:14 UTC, Mun09 commented on src/services/email.ts
> +      Buffer.from("R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==", "base64")
43바이트 짜리 gif 파일을 base64로 변환하면 저렇게 됩니다.

2025-07-29 10:12 UTC, kmc7468 commented on src/routes/index.ts
> +export { default as emailRouter } from "./emails";
여기서도 알파벳 순으로 부탁드려요~~

2025-07-29 10:16 UTC, kmc7468 commented on src/types/mongo.d.ts
> +  reportId?: Types.ObjectId;
이 친구는 optional인 이유가 있을까요?

2025-07-29 10:16 UTC, kmc7468 commented on src/views/emailPage.ts
> +        origin
여기서도 FRONT_URL 쓰면 좋을 것 같네요

2025-07-29 12:38 UTC, Mun09 commented on src/types/mongo.d.ts
> +  reportId?: Types.ObjectId;
없습니다. 고칠게요

2025-07-30 16:12 UTC, kmc7468 commented on src/types/mongo.d.ts
> +  reportId?: Types.ObjectId;
그러면 MongoDB 스키마에서도 required: true 주셔야 할 것 같습니다

2025-07-30 16:14 UTC, kmc7468 commented on src/loadenv.ts
> +export const FRONT_URL = process.env.FRONT_URL || "http://localhost:3000"; // optional
위에 jwt 쪽에서도 FRONT_URL를 바로 가져다 쓰는 곳이 있는데, 이 변수를 참조하도록 수정해 주세요!

2025-07-30 16:15 UTC, kmc7468 commented on src/loadenv.ts
> +export const FRONT_URL = process.env.FRONT_URL || "http://localhost:3000"; // optional
그리고 변수 이름이 다른 변수들이랑 컨벤션이 안 맞는 것 같습니다. `frontUrl` 등이 더 적절할 것 같아요

2025-07-30 16:15 UTC, kmc7468 commented on src/index.ts
> +// 이메일 수신 확인은 origin 검사 거치지 않기
주석 앞에 [Router] 달아주세요!

2025-07-30 16:17 UTC, kmc7468 commented on src/modules/stores/mongo.ts
> +  trackingId: { type: String, required: true }, // 이메일 id
unique: true를 주시면 조회 속도도 빨라지고, 혹시라도 중복되는 값이 DB에 삽입되는 문제도 해결할 수 있을 것 같네용

2025-07-30 16:17 UTC, kmc7468 commented on src/routes/docs/schemas/emailSchema.ts
> +    trackingId: z.string(), // 트래킹 ID
uuid 조건 걸어주시면 좋을 것 같아요!

2025-07-30 16:18 UTC, kmc7468 commented on src/routes/emails.ts
> +  "/open-tracking",
저희 컨벤션상 `openTracking` 이렇게 camelCase로 쓰는게 적절할 것 같아요

2025-07-30 16:19 UTC, kmc7468 commented on src/services/email.ts
> +    return res.status(400).send("Tracking ID missing");
저희 오류 메세지 보내는 컨벤션이랑 안 맞습니다! lottery 모듈 쪽 참고하셔서 비슷하게 맞춰주세용

2025-07-30 16:19 UTC, kmc7468 commented on src/services/email.ts
> +    res.send(
res를 통해 응답을 전송하는 경우 꼭 retrun을 붙여주세요! (catch문에서도 같이 부탁드립니당)

2025-07-30 16:21 UTC, kmc7468 commented on src/services/reports.js
> +    });
저희 새로운 문서를 삽입할 때에는 `new emailModel({ ... })` 로 생성한 뒤 `.save()` 함수 호출하는 식으로 컨벤션이 정해져 있습니다!

2025-07-30 16:22 UTC, kmc7468 commented on src/views/emailPage.ts
> +  origin: string
origin을 외부에서 전달 받는 것보다, 그냥 바로 FRONT_URL 값을 사용하는게 더 낫지 않을까요? origin이 바뀌는 경우가 딱히 없을 것 같아요

2025-08-01 10:21 UTC, kmc7468 commented on src/loadenv.ts
> +export const FRONT_URL = process.env.FRONT_URL || "http://localhost:3000"; // optional
처음 남겨드린 코멘트 반영이 안된 것 같습니다!

2025-08-01 10:24 UTC, kmc7468 commented on src/routes/emails.ts
> +router.get("/openTracking", validateQuery(emailZod.emailHandler), emailHandler);
Swagger 문서화도 부탁드립니다!

2025-08-01 10:25 UTC, kmc7468 commented on src/index.ts
> +app.use("/email", emailRouter);
`/emails` 가 다른거랑 일체감(?)이 더 좋을 것 같아요! (이메일 템플릿에서도 같이 수정 부탁드립니다)

2025-08-01 10:26 UTC, kmc7468 commented on src/services/email.ts
> +export const emailHandler: RequestHandler = async (req, res) => {
조금 더 직관적인 이름이면 좋을 것 같네요! 단순히 `emailHandler` 는 무엇을 하는지에 대해 잘 드러나지 않는 이름인 것 같아요.

2025-08-01 10:26 UTC, kmc7468 commented on src/services/email.ts
> +  }
라우터에서 이미 검증하고 들어오니까 필요 없는 코드인 것 같습니다

2025-08-01 10:27 UTC, kmc7468 commented on src/services/email.ts
> +      return res.status(404).send("Email/open-tracking: Tracking ID not found");
`Emails/openTracking` 이 컨벤션상 더 적절할 것 같네유

2025-08-03 13:05 UTC, kmc7468 commented on src/routes/docs/swaggerDocs.js
> +import emailsDocs from "./emails";
JS 파일에서는 CommonJS 방식의 모듈을 사용해야 해서, import 대신 require를 사용해 주셔야 합니다! API Docs의 경우 TS 마이그레이션 하지 않고 JS로 계속 유지하면 좋을 것 같습니다.

2025-08-03 13:08 UTC, kmc7468 commented on src/routes/docs/schemas/emailSchema.ts
> +export const emailSchema = zodToSchemaObject(emailZod);
`emailsZod` / `emailsSchema` 로 이름 맞춰주시는게 컨벤션상 맞을 것 같아요! (파일 이름도 emailsSchema.ts로 변경되어야 할 것 같습니다)

2025-08-03 13:09 UTC, kmc7468 commented on src/services/email.ts
이 파일도 이름이 emails.ts가 되어야 할 것 같네요! 불가피한 경우를 제외하면 라우터/서비스 로직 파일의 이름의 경우 복수형을 사용하고 있어요. (chats, reports, 등등)

2025-08-03 14:15 UTC, Mun09 commented on src/routes/docs/swaggerDocs.js
> +import emailsDocs from "./emails";
알겠습니다. 그러나 그동안 notice와 emails api는 swagger docs에서 보이지 않습니다.

2025-08-03 14:31 UTC, kmc7468 commented on src/routes/docs/swaggerDocs.js
> +import emailsDocs from "./emails";
JS로 바꿔주시거나, 아니면 require(...).default로 가져오시면 될거예요

2025-08-03 16:50 UTC, kmc7468 requested changes
수정 감사합니다! 이게 진짜 마지막 리뷰가 될 것 같습니다.
그리고 loadenv 쪽 제가 부탁드린거 아직 반영이 안됐어요...! jwt에 있는 issuer 쪽 수정이 필요합니다. 확인 부탁드려요

2025-08-03 16:50 UTC, kmc7468 commented on src/routes/docs/swaggerDocs.js
>  const noticeDocs = require("./notice");
수정하시는 김에 notice도 같이 부탁드려용~~

2025-08-03 16:50 UTC, kmc7468 commented on src/views/reportEmailPage.ts
> +import { frontUrl as origin } from "@/loadenv";
이 import는 이제 필요 없을 것 같네요

2025-08-03 16:50 UTC, kmc7468 commented on src/modules/slackNotification.ts
> +    `
이러면 Slack으로 전송될 때 마지막에 빈 줄이 하나 추가돼서 전송될 것 같네요. `의 위치를 다른 함수들이랑 똑같이 위로 옮겨주실 수 있나요?

2025-08-03 16:50 UTC, kmc7468 commented on src/modules/slackNotification.ts
> +  mailOption: SendMailOptions,
mailOption을 통째로 받는 것보다 메일 주소만 받는 것도 괜찮을 것 같아요

2025-08-04 02:23 UTC, Mun09 commented on src/views/reportEmailPage.ts
> +import { frontUrl as origin } from "@/loadenv";
reportEmailPage 코드에서 emailPage로 content 파라미터 넘길때 origin을 사용하는 곳이 있습니다.

2025-08-04 07:43 UTC, kmc7468 commented on src/services/emails.ts
> +    await trackingRecord.save();
이메일을 여러 번 열면 opendAt이 계속 업데이트 될 것 같습니다. isOpend === false인 경우에만 업데이트 해주면 어떨까요?

2025-08-04 07:46 UTC, kmc7468 commented on src/modules/slackNotification.ts
> +    기타: ${report.etcDetail}
신고가 접수되면 무조건 notifyReportToReportChannel 함수를 통해 슬랙에 정보가 전달되는데, 그러면 이 정보는 중복된 정보가 됩니다. 그래서 report._id 정도만 알려줘도 충분할 것 같다는 생각이 들었습니다

2025-08-04 08:13 UTC, kmc7468 commented on src/services/emails.ts
> +    await trackingRecord.save();
https://www.mongodb.com/ko-kr/docs/manual/reference/method/db.collection.updateOne/

이런거 써봐도 좋을 것 같아요. modifiedCount / matchedCount 값을 잘 비교하면 find + save를 updateOne 하나로 대체하여 더 안전하고 간결한 코드가 될 것 같습니다. (사실 find하고 update를 따로따로 처리하는게 동시성 관점에서 봤을 때 안전한 코드는 아니거든요 ㅠㅠ)

2025-08-05 13:50 UTC, merged