#54 Move profile from local to AWS (2)
sparcs-kaist/taxi-back pull request #81
Opened 2022-07-27 21:00 UTC by 14KGun

# Summary 

It closes #54 

# Extra info 

- Needs more than 2 reviewers? y
- Needs more than 10 minutes for review? y
- Needs to execute in order to review? y

# Further Work 

- 채팅 이미지도 S3 pre-signed url 사용하여 업로드

2022-07-27 21:09 UTC, withSang commented on src/db/patterns.js
> +    profileImgType: RegExp("^(image/png|image/jpg|image/jpeg)$"),
왜 소괄호로 감싸야 될까요? 😢

2022-07-27 21:21 UTC, withSang requested changes
우와 하룻밤 사이에 다 만드시다니 대단하세요!! 수고하셨습니다.
저도 이미지 업로드에서 입력값 검증은 같이 확인해봐야할 것 같아요!

2022-07-27 21:21 UTC, withSang commented on src/modules/modifyProfile.js
> +const defaultProfile = [
혹시 s3에서 가능한 모든 기본 프로필 사진의 목록을 불러와 사용하는 것은 어떨까요? 기본 프로필 사진 목록이 바뀌었을 때 좀 더 유연하게 대응할 수 있을 것 같아요

2022-07-27 21:21 UTC, withSang commented on src/route/docs/users.md
> +- 405 "s3 error"
s3 오류면 상태 코드를 500으로 하셔도 돼요!

2022-07-27 21:21 UTC, withSang commented on src/route/docs/users.md
> +- 405 "s3 error"
여기도 500 상태 코드가 좋다고 생각합니다!

2022-07-27 21:21 UTC, withSang commented on src/db/awsS3.js
> +    ACL: "public-read",
저희 버킷에 ACL이 설정되어 있지 않아서 없어야 해요!

2022-07-27 21:21 UTC, withSang commented on src/route/users.js
> +  body("type").matches(patterns.user.profileImgType),
검증이 이 것으로 충분할까요?
예를 들어, request body의 type에서 "image/jpeg"으로 명시한 다음 gif 파일을 업로드하면 업로드가 저희가 의도한 대로 실패할까요?

2022-07-27 21:28 UTC, withSang commented on src/route/users.js
> +  body("type").matches(patterns.user.profileImgType),
중요도가 낮아서 나중에 이슈를 추가하면 되겠습니당!

2022-07-27 21:36 UTC, 14KGun commented on src/db/patterns.js
> +    profileImgType: RegExp("^(image/png|image/jpg|image/jpeg)$"),
😄

2022-07-27 21:36 UTC, 14KGun commented on src/route/docs/users.md
> +- 405 "s3 error"
반영하였습니당

2022-07-27 21:36 UTC, 14KGun commented on src/route/docs/users.md
> +- 405 "s3 error"
반영하였습니당

2022-07-27 22:01 UTC, 14KGun commented on src/modules/modifyProfile.js
> +const defaultProfile = [
추후 auth.replace.js 를 지울 때 같이 작업하면 좋을 것 같습니다

2022-07-27 22:01 UTC, 14KGun commented on src/db/awsS3.js
> +    ACL: "public-read",
반영하였습니다!

2022-07-28 06:36 UTC, GrasshopperBears approved these changes
수고하셨습니다!

2022-07-28 06:36 UTC, GrasshopperBears commented on src/db/awsS3.js
> +        ["content-length-range", 1, 50 * 1024 * 1024], // Maximum file size is 50MB
50메가는 너무 크진 않을까요?

2022-07-28 11:23 UTC, 14KGun commented on src/db/awsS3.js
> +        ["content-length-range", 1, 50 * 1024 * 1024], // Maximum file size is 50MB
채팅 이미지 뿐만 아니라 프로필 사진 이미지 포함하여 크기 제한을 50MB로 생각하였습니다.
그리고 지금 코드 추가는 안되어있지만 프론트에서 이미지 압축을 20~30MB 정도로 압축하여 업로드를 하는 것도 계획 중에 있습니다.
괜찮지 않을까요???

2022-07-28 14:19 UTC, merged